// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/thompsonlogan/fitlytics/backend/internal/models/generated"
)

func newCoachAthlete(db *gorm.DB, opts ...gen.DOOption) coachAthlete {
	_coachAthlete := coachAthlete{}

	_coachAthlete.coachAthleteDo.UseDB(db, opts...)
	_coachAthlete.coachAthleteDo.UseModel(&generated.CoachAthlete{})

	tableName := _coachAthlete.coachAthleteDo.TableName()
	_coachAthlete.ALL = field.NewAsterisk(tableName)
	_coachAthlete.ID = field.NewField(tableName, "id")
	_coachAthlete.CoachUserID = field.NewField(tableName, "coach_user_id")
	_coachAthlete.AthleteUserID = field.NewField(tableName, "athlete_user_id")
	_coachAthlete.InvitedEmail = field.NewString(tableName, "invited_email")
	_coachAthlete.InviteTokenHash = field.NewString(tableName, "invite_token_hash")
	_coachAthlete.Status = field.NewString(tableName, "status")
	_coachAthlete.InvitedAt = field.NewTime(tableName, "invited_at")
	_coachAthlete.RespondedAt = field.NewTime(tableName, "responded_at")
	_coachAthlete.EndedAt = field.NewTime(tableName, "ended_at")
	_coachAthlete.CreatedAt = field.NewTime(tableName, "created_at")
	_coachAthlete.UpdatedAt = field.NewTime(tableName, "updated_at")
	_coachAthlete.DeletedAt = field.NewField(tableName, "deleted_at")

	_coachAthlete.fillFieldMap()

	return _coachAthlete
}

type coachAthlete struct {
	coachAthleteDo coachAthleteDo

	ALL             field.Asterisk
	ID              field.Field
	CoachUserID     field.Field
	AthleteUserID   field.Field
	InvitedEmail    field.String
	InviteTokenHash field.String
	Status          field.String
	InvitedAt       field.Time
	RespondedAt     field.Time
	EndedAt         field.Time
	CreatedAt       field.Time
	UpdatedAt       field.Time
	DeletedAt       field.Field

	fieldMap map[string]field.Expr
}

func (c coachAthlete) Table(newTableName string) *coachAthlete {
	c.coachAthleteDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c coachAthlete) As(alias string) *coachAthlete {
	c.coachAthleteDo.DO = *(c.coachAthleteDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *coachAthlete) updateTableName(table string) *coachAthlete {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewField(table, "id")
	c.CoachUserID = field.NewField(table, "coach_user_id")
	c.AthleteUserID = field.NewField(table, "athlete_user_id")
	c.InvitedEmail = field.NewString(table, "invited_email")
	c.InviteTokenHash = field.NewString(table, "invite_token_hash")
	c.Status = field.NewString(table, "status")
	c.InvitedAt = field.NewTime(table, "invited_at")
	c.RespondedAt = field.NewTime(table, "responded_at")
	c.EndedAt = field.NewTime(table, "ended_at")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")
	c.DeletedAt = field.NewField(table, "deleted_at")

	c.fillFieldMap()

	return c
}

func (c *coachAthlete) WithContext(ctx context.Context) *coachAthleteDo {
	return c.coachAthleteDo.WithContext(ctx)
}

func (c coachAthlete) TableName() string { return c.coachAthleteDo.TableName() }

func (c coachAthlete) Alias() string { return c.coachAthleteDo.Alias() }

func (c coachAthlete) Columns(cols ...field.Expr) gen.Columns {
	return c.coachAthleteDo.Columns(cols...)
}

func (c *coachAthlete) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *coachAthlete) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 12)
	c.fieldMap["id"] = c.ID
	c.fieldMap["coach_user_id"] = c.CoachUserID
	c.fieldMap["athlete_user_id"] = c.AthleteUserID
	c.fieldMap["invited_email"] = c.InvitedEmail
	c.fieldMap["invite_token_hash"] = c.InviteTokenHash
	c.fieldMap["status"] = c.Status
	c.fieldMap["invited_at"] = c.InvitedAt
	c.fieldMap["responded_at"] = c.RespondedAt
	c.fieldMap["ended_at"] = c.EndedAt
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
	c.fieldMap["deleted_at"] = c.DeletedAt
}

func (c coachAthlete) clone(db *gorm.DB) coachAthlete {
	c.coachAthleteDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c coachAthlete) replaceDB(db *gorm.DB) coachAthlete {
	c.coachAthleteDo.ReplaceDB(db)
	return c
}

type coachAthleteDo struct{ gen.DO }

func (c coachAthleteDo) Debug() *coachAthleteDo {
	return c.withDO(c.DO.Debug())
}

func (c coachAthleteDo) WithContext(ctx context.Context) *coachAthleteDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c coachAthleteDo) ReadDB() *coachAthleteDo {
	return c.Clauses(dbresolver.Read)
}

func (c coachAthleteDo) WriteDB() *coachAthleteDo {
	return c.Clauses(dbresolver.Write)
}

func (c coachAthleteDo) Session(config *gorm.Session) *coachAthleteDo {
	return c.withDO(c.DO.Session(config))
}

func (c coachAthleteDo) Clauses(conds ...clause.Expression) *coachAthleteDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c coachAthleteDo) Returning(value interface{}, columns ...string) *coachAthleteDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c coachAthleteDo) Not(conds ...gen.Condition) *coachAthleteDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c coachAthleteDo) Or(conds ...gen.Condition) *coachAthleteDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c coachAthleteDo) Select(conds ...field.Expr) *coachAthleteDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c coachAthleteDo) Where(conds ...gen.Condition) *coachAthleteDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c coachAthleteDo) Order(conds ...field.Expr) *coachAthleteDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c coachAthleteDo) Distinct(cols ...field.Expr) *coachAthleteDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c coachAthleteDo) Omit(cols ...field.Expr) *coachAthleteDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c coachAthleteDo) Join(table schema.Tabler, on ...field.Expr) *coachAthleteDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c coachAthleteDo) LeftJoin(table schema.Tabler, on ...field.Expr) *coachAthleteDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c coachAthleteDo) RightJoin(table schema.Tabler, on ...field.Expr) *coachAthleteDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c coachAthleteDo) Group(cols ...field.Expr) *coachAthleteDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c coachAthleteDo) Having(conds ...gen.Condition) *coachAthleteDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c coachAthleteDo) Limit(limit int) *coachAthleteDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c coachAthleteDo) Offset(offset int) *coachAthleteDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c coachAthleteDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *coachAthleteDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c coachAthleteDo) Unscoped() *coachAthleteDo {
	return c.withDO(c.DO.Unscoped())
}

func (c coachAthleteDo) Create(values ...*generated.CoachAthlete) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c coachAthleteDo) CreateInBatches(values []*generated.CoachAthlete, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c coachAthleteDo) Save(values ...*generated.CoachAthlete) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c coachAthleteDo) First() (*generated.CoachAthlete, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*generated.CoachAthlete), nil
	}
}

func (c coachAthleteDo) Take() (*generated.CoachAthlete, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*generated.CoachAthlete), nil
	}
}

func (c coachAthleteDo) Last() (*generated.CoachAthlete, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*generated.CoachAthlete), nil
	}
}

func (c coachAthleteDo) Find() ([]*generated.CoachAthlete, error) {
	result, err := c.DO.Find()
	return result.([]*generated.CoachAthlete), err
}

func (c coachAthleteDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*generated.CoachAthlete, err error) {
	buf := make([]*generated.CoachAthlete, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c coachAthleteDo) FindInBatches(result *[]*generated.CoachAthlete, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c coachAthleteDo) Attrs(attrs ...field.AssignExpr) *coachAthleteDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c coachAthleteDo) Assign(attrs ...field.AssignExpr) *coachAthleteDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c coachAthleteDo) Joins(fields ...field.RelationField) *coachAthleteDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c coachAthleteDo) Preload(fields ...field.RelationField) *coachAthleteDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c coachAthleteDo) FirstOrInit() (*generated.CoachAthlete, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*generated.CoachAthlete), nil
	}
}

func (c coachAthleteDo) FirstOrCreate() (*generated.CoachAthlete, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*generated.CoachAthlete), nil
	}
}

func (c coachAthleteDo) FindByPage(offset int, limit int) (result []*generated.CoachAthlete, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c coachAthleteDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c coachAthleteDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c coachAthleteDo) Delete(models ...*generated.CoachAthlete) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *coachAthleteDo) withDO(do gen.Dao) *coachAthleteDo {
	c.DO = *do.(*gen.DO)
	return c
}
