// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/thompsonlogan/fitlytics/backend/internal/models/generated"
)

func newCoachNote(db *gorm.DB, opts ...gen.DOOption) coachNote {
	_coachNote := coachNote{}

	_coachNote.coachNoteDo.UseDB(db, opts...)
	_coachNote.coachNoteDo.UseModel(&generated.CoachNote{})

	tableName := _coachNote.coachNoteDo.TableName()
	_coachNote.ALL = field.NewAsterisk(tableName)
	_coachNote.ID = field.NewField(tableName, "id")
	_coachNote.CoachAthleteID = field.NewField(tableName, "coach_athlete_id")
	_coachNote.AuthorUserID = field.NewField(tableName, "author_user_id")
	_coachNote.Body = field.NewString(tableName, "body")
	_coachNote.SetVideoID = field.NewField(tableName, "set_video_id")
	_coachNote.CreatedAt = field.NewTime(tableName, "created_at")
	_coachNote.UpdatedAt = field.NewTime(tableName, "updated_at")
	_coachNote.DeletedAt = field.NewField(tableName, "deleted_at")

	_coachNote.fillFieldMap()

	return _coachNote
}

type coachNote struct {
	coachNoteDo coachNoteDo

	ALL            field.Asterisk
	ID             field.Field
	CoachAthleteID field.Field
	AuthorUserID   field.Field
	Body           field.String
	SetVideoID     field.Field
	CreatedAt      field.Time
	UpdatedAt      field.Time
	DeletedAt      field.Field

	fieldMap map[string]field.Expr
}

func (c coachNote) Table(newTableName string) *coachNote {
	c.coachNoteDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c coachNote) As(alias string) *coachNote {
	c.coachNoteDo.DO = *(c.coachNoteDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *coachNote) updateTableName(table string) *coachNote {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewField(table, "id")
	c.CoachAthleteID = field.NewField(table, "coach_athlete_id")
	c.AuthorUserID = field.NewField(table, "author_user_id")
	c.Body = field.NewString(table, "body")
	c.SetVideoID = field.NewField(table, "set_video_id")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")
	c.DeletedAt = field.NewField(table, "deleted_at")

	c.fillFieldMap()

	return c
}

func (c *coachNote) WithContext(ctx context.Context) *coachNoteDo {
	return c.coachNoteDo.WithContext(ctx)
}

func (c coachNote) TableName() string { return c.coachNoteDo.TableName() }

func (c coachNote) Alias() string { return c.coachNoteDo.Alias() }

func (c coachNote) Columns(cols ...field.Expr) gen.Columns { return c.coachNoteDo.Columns(cols...) }

func (c *coachNote) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *coachNote) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 8)
	c.fieldMap["id"] = c.ID
	c.fieldMap["coach_athlete_id"] = c.CoachAthleteID
	c.fieldMap["author_user_id"] = c.AuthorUserID
	c.fieldMap["body"] = c.Body
	c.fieldMap["set_video_id"] = c.SetVideoID
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
	c.fieldMap["deleted_at"] = c.DeletedAt
}

func (c coachNote) clone(db *gorm.DB) coachNote {
	c.coachNoteDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c coachNote) replaceDB(db *gorm.DB) coachNote {
	c.coachNoteDo.ReplaceDB(db)
	return c
}

type coachNoteDo struct{ gen.DO }

func (c coachNoteDo) Debug() *coachNoteDo {
	return c.withDO(c.DO.Debug())
}

func (c coachNoteDo) WithContext(ctx context.Context) *coachNoteDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c coachNoteDo) ReadDB() *coachNoteDo {
	return c.Clauses(dbresolver.Read)
}

func (c coachNoteDo) WriteDB() *coachNoteDo {
	return c.Clauses(dbresolver.Write)
}

func (c coachNoteDo) Session(config *gorm.Session) *coachNoteDo {
	return c.withDO(c.DO.Session(config))
}

func (c coachNoteDo) Clauses(conds ...clause.Expression) *coachNoteDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c coachNoteDo) Returning(value interface{}, columns ...string) *coachNoteDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c coachNoteDo) Not(conds ...gen.Condition) *coachNoteDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c coachNoteDo) Or(conds ...gen.Condition) *coachNoteDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c coachNoteDo) Select(conds ...field.Expr) *coachNoteDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c coachNoteDo) Where(conds ...gen.Condition) *coachNoteDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c coachNoteDo) Order(conds ...field.Expr) *coachNoteDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c coachNoteDo) Distinct(cols ...field.Expr) *coachNoteDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c coachNoteDo) Omit(cols ...field.Expr) *coachNoteDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c coachNoteDo) Join(table schema.Tabler, on ...field.Expr) *coachNoteDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c coachNoteDo) LeftJoin(table schema.Tabler, on ...field.Expr) *coachNoteDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c coachNoteDo) RightJoin(table schema.Tabler, on ...field.Expr) *coachNoteDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c coachNoteDo) Group(cols ...field.Expr) *coachNoteDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c coachNoteDo) Having(conds ...gen.Condition) *coachNoteDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c coachNoteDo) Limit(limit int) *coachNoteDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c coachNoteDo) Offset(offset int) *coachNoteDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c coachNoteDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *coachNoteDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c coachNoteDo) Unscoped() *coachNoteDo {
	return c.withDO(c.DO.Unscoped())
}

func (c coachNoteDo) Create(values ...*generated.CoachNote) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c coachNoteDo) CreateInBatches(values []*generated.CoachNote, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c coachNoteDo) Save(values ...*generated.CoachNote) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c coachNoteDo) First() (*generated.CoachNote, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*generated.CoachNote), nil
	}
}

func (c coachNoteDo) Take() (*generated.CoachNote, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*generated.CoachNote), nil
	}
}

func (c coachNoteDo) Last() (*generated.CoachNote, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*generated.CoachNote), nil
	}
}

func (c coachNoteDo) Find() ([]*generated.CoachNote, error) {
	result, err := c.DO.Find()
	return result.([]*generated.CoachNote), err
}

func (c coachNoteDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*generated.CoachNote, err error) {
	buf := make([]*generated.CoachNote, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c coachNoteDo) FindInBatches(result *[]*generated.CoachNote, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c coachNoteDo) Attrs(attrs ...field.AssignExpr) *coachNoteDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c coachNoteDo) Assign(attrs ...field.AssignExpr) *coachNoteDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c coachNoteDo) Joins(fields ...field.RelationField) *coachNoteDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c coachNoteDo) Preload(fields ...field.RelationField) *coachNoteDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c coachNoteDo) FirstOrInit() (*generated.CoachNote, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*generated.CoachNote), nil
	}
}

func (c coachNoteDo) FirstOrCreate() (*generated.CoachNote, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*generated.CoachNote), nil
	}
}

func (c coachNoteDo) FindByPage(offset int, limit int) (result []*generated.CoachNote, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c coachNoteDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c coachNoteDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c coachNoteDo) Delete(models ...*generated.CoachNote) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *coachNoteDo) withDO(do gen.Dao) *coachNoteDo {
	c.DO = *do.(*gen.DO)
	return c
}
