// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/thompsonlogan/fitlytics/backend/internal/models/generated"
)

func newEquipment(db *gorm.DB, opts ...gen.DOOption) equipment {
	_equipment := equipment{}

	_equipment.equipmentDo.UseDB(db, opts...)
	_equipment.equipmentDo.UseModel(&generated.Equipment{})

	tableName := _equipment.equipmentDo.TableName()
	_equipment.ALL = field.NewAsterisk(tableName)
	_equipment.ID = field.NewField(tableName, "id")
	_equipment.Slug = field.NewString(tableName, "slug")
	_equipment.Name = field.NewString(tableName, "name")
	_equipment.CreatedAt = field.NewTime(tableName, "created_at")
	_equipment.UpdatedAt = field.NewTime(tableName, "updated_at")

	_equipment.fillFieldMap()

	return _equipment
}

type equipment struct {
	equipmentDo equipmentDo

	ALL       field.Asterisk
	ID        field.Field
	Slug      field.String
	Name      field.String
	CreatedAt field.Time
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

func (e equipment) Table(newTableName string) *equipment {
	e.equipmentDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e equipment) As(alias string) *equipment {
	e.equipmentDo.DO = *(e.equipmentDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *equipment) updateTableName(table string) *equipment {
	e.ALL = field.NewAsterisk(table)
	e.ID = field.NewField(table, "id")
	e.Slug = field.NewString(table, "slug")
	e.Name = field.NewString(table, "name")
	e.CreatedAt = field.NewTime(table, "created_at")
	e.UpdatedAt = field.NewTime(table, "updated_at")

	e.fillFieldMap()

	return e
}

func (e *equipment) WithContext(ctx context.Context) *equipmentDo {
	return e.equipmentDo.WithContext(ctx)
}

func (e equipment) TableName() string { return e.equipmentDo.TableName() }

func (e equipment) Alias() string { return e.equipmentDo.Alias() }

func (e equipment) Columns(cols ...field.Expr) gen.Columns { return e.equipmentDo.Columns(cols...) }

func (e *equipment) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *equipment) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 5)
	e.fieldMap["id"] = e.ID
	e.fieldMap["slug"] = e.Slug
	e.fieldMap["name"] = e.Name
	e.fieldMap["created_at"] = e.CreatedAt
	e.fieldMap["updated_at"] = e.UpdatedAt
}

func (e equipment) clone(db *gorm.DB) equipment {
	e.equipmentDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e equipment) replaceDB(db *gorm.DB) equipment {
	e.equipmentDo.ReplaceDB(db)
	return e
}

type equipmentDo struct{ gen.DO }

func (e equipmentDo) Debug() *equipmentDo {
	return e.withDO(e.DO.Debug())
}

func (e equipmentDo) WithContext(ctx context.Context) *equipmentDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e equipmentDo) ReadDB() *equipmentDo {
	return e.Clauses(dbresolver.Read)
}

func (e equipmentDo) WriteDB() *equipmentDo {
	return e.Clauses(dbresolver.Write)
}

func (e equipmentDo) Session(config *gorm.Session) *equipmentDo {
	return e.withDO(e.DO.Session(config))
}

func (e equipmentDo) Clauses(conds ...clause.Expression) *equipmentDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e equipmentDo) Returning(value interface{}, columns ...string) *equipmentDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e equipmentDo) Not(conds ...gen.Condition) *equipmentDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e equipmentDo) Or(conds ...gen.Condition) *equipmentDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e equipmentDo) Select(conds ...field.Expr) *equipmentDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e equipmentDo) Where(conds ...gen.Condition) *equipmentDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e equipmentDo) Order(conds ...field.Expr) *equipmentDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e equipmentDo) Distinct(cols ...field.Expr) *equipmentDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e equipmentDo) Omit(cols ...field.Expr) *equipmentDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e equipmentDo) Join(table schema.Tabler, on ...field.Expr) *equipmentDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e equipmentDo) LeftJoin(table schema.Tabler, on ...field.Expr) *equipmentDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e equipmentDo) RightJoin(table schema.Tabler, on ...field.Expr) *equipmentDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e equipmentDo) Group(cols ...field.Expr) *equipmentDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e equipmentDo) Having(conds ...gen.Condition) *equipmentDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e equipmentDo) Limit(limit int) *equipmentDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e equipmentDo) Offset(offset int) *equipmentDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e equipmentDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *equipmentDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e equipmentDo) Unscoped() *equipmentDo {
	return e.withDO(e.DO.Unscoped())
}

func (e equipmentDo) Create(values ...*generated.Equipment) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e equipmentDo) CreateInBatches(values []*generated.Equipment, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e equipmentDo) Save(values ...*generated.Equipment) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e equipmentDo) First() (*generated.Equipment, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*generated.Equipment), nil
	}
}

func (e equipmentDo) Take() (*generated.Equipment, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*generated.Equipment), nil
	}
}

func (e equipmentDo) Last() (*generated.Equipment, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*generated.Equipment), nil
	}
}

func (e equipmentDo) Find() ([]*generated.Equipment, error) {
	result, err := e.DO.Find()
	return result.([]*generated.Equipment), err
}

func (e equipmentDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*generated.Equipment, err error) {
	buf := make([]*generated.Equipment, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e equipmentDo) FindInBatches(result *[]*generated.Equipment, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e equipmentDo) Attrs(attrs ...field.AssignExpr) *equipmentDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e equipmentDo) Assign(attrs ...field.AssignExpr) *equipmentDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e equipmentDo) Joins(fields ...field.RelationField) *equipmentDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e equipmentDo) Preload(fields ...field.RelationField) *equipmentDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e equipmentDo) FirstOrInit() (*generated.Equipment, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*generated.Equipment), nil
	}
}

func (e equipmentDo) FirstOrCreate() (*generated.Equipment, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*generated.Equipment), nil
	}
}

func (e equipmentDo) FindByPage(offset int, limit int) (result []*generated.Equipment, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e equipmentDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e equipmentDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e equipmentDo) Delete(models ...*generated.Equipment) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *equipmentDo) withDO(do gen.Dao) *equipmentDo {
	e.DO = *do.(*gen.DO)
	return e
}
