// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/thompsonlogan/fitlytics/backend/internal/models/generated"
)

func newExercise(db *gorm.DB, opts ...gen.DOOption) exercise {
	_exercise := exercise{}

	_exercise.exerciseDo.UseDB(db, opts...)
	_exercise.exerciseDo.UseModel(&generated.Exercise{})

	tableName := _exercise.exerciseDo.TableName()
	_exercise.ALL = field.NewAsterisk(tableName)
	_exercise.ID = field.NewField(tableName, "id")
	_exercise.CanonicalID = field.NewField(tableName, "canonical_id")
	_exercise.CanonicalRefFlag = field.NewBool(tableName, "canonical_ref_flag")
	_exercise.CreatedByUserID = field.NewField(tableName, "created_by_user_id")
	_exercise.IsCanonical = field.NewBool(tableName, "is_canonical")
	_exercise.Name = field.NewString(tableName, "name")
	_exercise.Slug = field.NewString(tableName, "slug")
	_exercise.PrimaryMuscles = field.NewField(tableName, "primary_muscles")
	_exercise.SecondaryMuscles = field.NewField(tableName, "secondary_muscles")
	_exercise.MovementPattern = field.NewString(tableName, "movement_pattern")
	_exercise.IsCompound = field.NewBool(tableName, "is_compound")
	_exercise.LoadType = field.NewString(tableName, "load_type")
	_exercise.DefaultLoadModifier = field.NewString(tableName, "default_load_modifier")
	_exercise.Notes = field.NewString(tableName, "notes")
	_exercise.CreatedAt = field.NewTime(tableName, "created_at")
	_exercise.UpdatedAt = field.NewTime(tableName, "updated_at")
	_exercise.DeletedAt = field.NewField(tableName, "deleted_at")

	_exercise.fillFieldMap()

	return _exercise
}

type exercise struct {
	exerciseDo exerciseDo

	ALL                 field.Asterisk
	ID                  field.Field
	CanonicalID         field.Field
	CanonicalRefFlag    field.Bool
	CreatedByUserID     field.Field
	IsCanonical         field.Bool
	Name                field.String
	Slug                field.String
	PrimaryMuscles      field.Field
	SecondaryMuscles    field.Field
	MovementPattern     field.String
	IsCompound          field.Bool
	LoadType            field.String
	DefaultLoadModifier field.String
	Notes               field.String
	CreatedAt           field.Time
	UpdatedAt           field.Time
	DeletedAt           field.Field

	fieldMap map[string]field.Expr
}

func (e exercise) Table(newTableName string) *exercise {
	e.exerciseDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e exercise) As(alias string) *exercise {
	e.exerciseDo.DO = *(e.exerciseDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *exercise) updateTableName(table string) *exercise {
	e.ALL = field.NewAsterisk(table)
	e.ID = field.NewField(table, "id")
	e.CanonicalID = field.NewField(table, "canonical_id")
	e.CanonicalRefFlag = field.NewBool(table, "canonical_ref_flag")
	e.CreatedByUserID = field.NewField(table, "created_by_user_id")
	e.IsCanonical = field.NewBool(table, "is_canonical")
	e.Name = field.NewString(table, "name")
	e.Slug = field.NewString(table, "slug")
	e.PrimaryMuscles = field.NewField(table, "primary_muscles")
	e.SecondaryMuscles = field.NewField(table, "secondary_muscles")
	e.MovementPattern = field.NewString(table, "movement_pattern")
	e.IsCompound = field.NewBool(table, "is_compound")
	e.LoadType = field.NewString(table, "load_type")
	e.DefaultLoadModifier = field.NewString(table, "default_load_modifier")
	e.Notes = field.NewString(table, "notes")
	e.CreatedAt = field.NewTime(table, "created_at")
	e.UpdatedAt = field.NewTime(table, "updated_at")
	e.DeletedAt = field.NewField(table, "deleted_at")

	e.fillFieldMap()

	return e
}

func (e *exercise) WithContext(ctx context.Context) *exerciseDo { return e.exerciseDo.WithContext(ctx) }

func (e exercise) TableName() string { return e.exerciseDo.TableName() }

func (e exercise) Alias() string { return e.exerciseDo.Alias() }

func (e exercise) Columns(cols ...field.Expr) gen.Columns { return e.exerciseDo.Columns(cols...) }

func (e *exercise) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *exercise) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 17)
	e.fieldMap["id"] = e.ID
	e.fieldMap["canonical_id"] = e.CanonicalID
	e.fieldMap["canonical_ref_flag"] = e.CanonicalRefFlag
	e.fieldMap["created_by_user_id"] = e.CreatedByUserID
	e.fieldMap["is_canonical"] = e.IsCanonical
	e.fieldMap["name"] = e.Name
	e.fieldMap["slug"] = e.Slug
	e.fieldMap["primary_muscles"] = e.PrimaryMuscles
	e.fieldMap["secondary_muscles"] = e.SecondaryMuscles
	e.fieldMap["movement_pattern"] = e.MovementPattern
	e.fieldMap["is_compound"] = e.IsCompound
	e.fieldMap["load_type"] = e.LoadType
	e.fieldMap["default_load_modifier"] = e.DefaultLoadModifier
	e.fieldMap["notes"] = e.Notes
	e.fieldMap["created_at"] = e.CreatedAt
	e.fieldMap["updated_at"] = e.UpdatedAt
	e.fieldMap["deleted_at"] = e.DeletedAt
}

func (e exercise) clone(db *gorm.DB) exercise {
	e.exerciseDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e exercise) replaceDB(db *gorm.DB) exercise {
	e.exerciseDo.ReplaceDB(db)
	return e
}

type exerciseDo struct{ gen.DO }

func (e exerciseDo) Debug() *exerciseDo {
	return e.withDO(e.DO.Debug())
}

func (e exerciseDo) WithContext(ctx context.Context) *exerciseDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e exerciseDo) ReadDB() *exerciseDo {
	return e.Clauses(dbresolver.Read)
}

func (e exerciseDo) WriteDB() *exerciseDo {
	return e.Clauses(dbresolver.Write)
}

func (e exerciseDo) Session(config *gorm.Session) *exerciseDo {
	return e.withDO(e.DO.Session(config))
}

func (e exerciseDo) Clauses(conds ...clause.Expression) *exerciseDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e exerciseDo) Returning(value interface{}, columns ...string) *exerciseDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e exerciseDo) Not(conds ...gen.Condition) *exerciseDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e exerciseDo) Or(conds ...gen.Condition) *exerciseDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e exerciseDo) Select(conds ...field.Expr) *exerciseDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e exerciseDo) Where(conds ...gen.Condition) *exerciseDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e exerciseDo) Order(conds ...field.Expr) *exerciseDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e exerciseDo) Distinct(cols ...field.Expr) *exerciseDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e exerciseDo) Omit(cols ...field.Expr) *exerciseDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e exerciseDo) Join(table schema.Tabler, on ...field.Expr) *exerciseDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e exerciseDo) LeftJoin(table schema.Tabler, on ...field.Expr) *exerciseDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e exerciseDo) RightJoin(table schema.Tabler, on ...field.Expr) *exerciseDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e exerciseDo) Group(cols ...field.Expr) *exerciseDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e exerciseDo) Having(conds ...gen.Condition) *exerciseDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e exerciseDo) Limit(limit int) *exerciseDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e exerciseDo) Offset(offset int) *exerciseDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e exerciseDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *exerciseDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e exerciseDo) Unscoped() *exerciseDo {
	return e.withDO(e.DO.Unscoped())
}

func (e exerciseDo) Create(values ...*generated.Exercise) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e exerciseDo) CreateInBatches(values []*generated.Exercise, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e exerciseDo) Save(values ...*generated.Exercise) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e exerciseDo) First() (*generated.Exercise, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*generated.Exercise), nil
	}
}

func (e exerciseDo) Take() (*generated.Exercise, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*generated.Exercise), nil
	}
}

func (e exerciseDo) Last() (*generated.Exercise, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*generated.Exercise), nil
	}
}

func (e exerciseDo) Find() ([]*generated.Exercise, error) {
	result, err := e.DO.Find()
	return result.([]*generated.Exercise), err
}

func (e exerciseDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*generated.Exercise, err error) {
	buf := make([]*generated.Exercise, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e exerciseDo) FindInBatches(result *[]*generated.Exercise, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e exerciseDo) Attrs(attrs ...field.AssignExpr) *exerciseDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e exerciseDo) Assign(attrs ...field.AssignExpr) *exerciseDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e exerciseDo) Joins(fields ...field.RelationField) *exerciseDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e exerciseDo) Preload(fields ...field.RelationField) *exerciseDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e exerciseDo) FirstOrInit() (*generated.Exercise, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*generated.Exercise), nil
	}
}

func (e exerciseDo) FirstOrCreate() (*generated.Exercise, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*generated.Exercise), nil
	}
}

func (e exerciseDo) FindByPage(offset int, limit int) (result []*generated.Exercise, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e exerciseDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e exerciseDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e exerciseDo) Delete(models ...*generated.Exercise) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *exerciseDo) withDO(do gen.Dao) *exerciseDo {
	e.DO = *do.(*gen.DO)
	return e
}
