// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/thompsonlogan/fitlytics/backend/internal/models/generated"
)

func newExerciseEquipment(db *gorm.DB, opts ...gen.DOOption) exerciseEquipment {
	_exerciseEquipment := exerciseEquipment{}

	_exerciseEquipment.exerciseEquipmentDo.UseDB(db, opts...)
	_exerciseEquipment.exerciseEquipmentDo.UseModel(&generated.ExerciseEquipment{})

	tableName := _exerciseEquipment.exerciseEquipmentDo.TableName()
	_exerciseEquipment.ALL = field.NewAsterisk(tableName)
	_exerciseEquipment.ExerciseID = field.NewField(tableName, "exercise_id")
	_exerciseEquipment.EquipmentID = field.NewField(tableName, "equipment_id")

	_exerciseEquipment.fillFieldMap()

	return _exerciseEquipment
}

type exerciseEquipment struct {
	exerciseEquipmentDo exerciseEquipmentDo

	ALL         field.Asterisk
	ExerciseID  field.Field
	EquipmentID field.Field

	fieldMap map[string]field.Expr
}

func (e exerciseEquipment) Table(newTableName string) *exerciseEquipment {
	e.exerciseEquipmentDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e exerciseEquipment) As(alias string) *exerciseEquipment {
	e.exerciseEquipmentDo.DO = *(e.exerciseEquipmentDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *exerciseEquipment) updateTableName(table string) *exerciseEquipment {
	e.ALL = field.NewAsterisk(table)
	e.ExerciseID = field.NewField(table, "exercise_id")
	e.EquipmentID = field.NewField(table, "equipment_id")

	e.fillFieldMap()

	return e
}

func (e *exerciseEquipment) WithContext(ctx context.Context) *exerciseEquipmentDo {
	return e.exerciseEquipmentDo.WithContext(ctx)
}

func (e exerciseEquipment) TableName() string { return e.exerciseEquipmentDo.TableName() }

func (e exerciseEquipment) Alias() string { return e.exerciseEquipmentDo.Alias() }

func (e exerciseEquipment) Columns(cols ...field.Expr) gen.Columns {
	return e.exerciseEquipmentDo.Columns(cols...)
}

func (e *exerciseEquipment) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *exerciseEquipment) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 2)
	e.fieldMap["exercise_id"] = e.ExerciseID
	e.fieldMap["equipment_id"] = e.EquipmentID
}

func (e exerciseEquipment) clone(db *gorm.DB) exerciseEquipment {
	e.exerciseEquipmentDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e exerciseEquipment) replaceDB(db *gorm.DB) exerciseEquipment {
	e.exerciseEquipmentDo.ReplaceDB(db)
	return e
}

type exerciseEquipmentDo struct{ gen.DO }

func (e exerciseEquipmentDo) Debug() *exerciseEquipmentDo {
	return e.withDO(e.DO.Debug())
}

func (e exerciseEquipmentDo) WithContext(ctx context.Context) *exerciseEquipmentDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e exerciseEquipmentDo) ReadDB() *exerciseEquipmentDo {
	return e.Clauses(dbresolver.Read)
}

func (e exerciseEquipmentDo) WriteDB() *exerciseEquipmentDo {
	return e.Clauses(dbresolver.Write)
}

func (e exerciseEquipmentDo) Session(config *gorm.Session) *exerciseEquipmentDo {
	return e.withDO(e.DO.Session(config))
}

func (e exerciseEquipmentDo) Clauses(conds ...clause.Expression) *exerciseEquipmentDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e exerciseEquipmentDo) Returning(value interface{}, columns ...string) *exerciseEquipmentDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e exerciseEquipmentDo) Not(conds ...gen.Condition) *exerciseEquipmentDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e exerciseEquipmentDo) Or(conds ...gen.Condition) *exerciseEquipmentDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e exerciseEquipmentDo) Select(conds ...field.Expr) *exerciseEquipmentDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e exerciseEquipmentDo) Where(conds ...gen.Condition) *exerciseEquipmentDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e exerciseEquipmentDo) Order(conds ...field.Expr) *exerciseEquipmentDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e exerciseEquipmentDo) Distinct(cols ...field.Expr) *exerciseEquipmentDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e exerciseEquipmentDo) Omit(cols ...field.Expr) *exerciseEquipmentDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e exerciseEquipmentDo) Join(table schema.Tabler, on ...field.Expr) *exerciseEquipmentDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e exerciseEquipmentDo) LeftJoin(table schema.Tabler, on ...field.Expr) *exerciseEquipmentDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e exerciseEquipmentDo) RightJoin(table schema.Tabler, on ...field.Expr) *exerciseEquipmentDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e exerciseEquipmentDo) Group(cols ...field.Expr) *exerciseEquipmentDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e exerciseEquipmentDo) Having(conds ...gen.Condition) *exerciseEquipmentDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e exerciseEquipmentDo) Limit(limit int) *exerciseEquipmentDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e exerciseEquipmentDo) Offset(offset int) *exerciseEquipmentDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e exerciseEquipmentDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *exerciseEquipmentDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e exerciseEquipmentDo) Unscoped() *exerciseEquipmentDo {
	return e.withDO(e.DO.Unscoped())
}

func (e exerciseEquipmentDo) Create(values ...*generated.ExerciseEquipment) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e exerciseEquipmentDo) CreateInBatches(values []*generated.ExerciseEquipment, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e exerciseEquipmentDo) Save(values ...*generated.ExerciseEquipment) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e exerciseEquipmentDo) First() (*generated.ExerciseEquipment, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*generated.ExerciseEquipment), nil
	}
}

func (e exerciseEquipmentDo) Take() (*generated.ExerciseEquipment, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*generated.ExerciseEquipment), nil
	}
}

func (e exerciseEquipmentDo) Last() (*generated.ExerciseEquipment, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*generated.ExerciseEquipment), nil
	}
}

func (e exerciseEquipmentDo) Find() ([]*generated.ExerciseEquipment, error) {
	result, err := e.DO.Find()
	return result.([]*generated.ExerciseEquipment), err
}

func (e exerciseEquipmentDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*generated.ExerciseEquipment, err error) {
	buf := make([]*generated.ExerciseEquipment, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e exerciseEquipmentDo) FindInBatches(result *[]*generated.ExerciseEquipment, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e exerciseEquipmentDo) Attrs(attrs ...field.AssignExpr) *exerciseEquipmentDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e exerciseEquipmentDo) Assign(attrs ...field.AssignExpr) *exerciseEquipmentDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e exerciseEquipmentDo) Joins(fields ...field.RelationField) *exerciseEquipmentDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e exerciseEquipmentDo) Preload(fields ...field.RelationField) *exerciseEquipmentDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e exerciseEquipmentDo) FirstOrInit() (*generated.ExerciseEquipment, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*generated.ExerciseEquipment), nil
	}
}

func (e exerciseEquipmentDo) FirstOrCreate() (*generated.ExerciseEquipment, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*generated.ExerciseEquipment), nil
	}
}

func (e exerciseEquipmentDo) FindByPage(offset int, limit int) (result []*generated.ExerciseEquipment, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e exerciseEquipmentDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e exerciseEquipmentDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e exerciseEquipmentDo) Delete(models ...*generated.ExerciseEquipment) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *exerciseEquipmentDo) withDO(do gen.Dao) *exerciseEquipmentDo {
	e.DO = *do.(*gen.DO)
	return e
}
