// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                db,
		CoachAthlete:      newCoachAthlete(db, opts...),
		Equipment:         newEquipment(db, opts...),
		Exercise:          newExercise(db, opts...),
		ExerciseEquipment: newExerciseEquipment(db, opts...),
		Program:           newProgram(db, opts...),
		ProgramDay:        newProgramDay(db, opts...),
		ProgramExercise:   newProgramExercise(db, opts...),
		ProgramSet:        newProgramSet(db, opts...),
		ProgramSetGroup:   newProgramSetGroup(db, opts...),
		ProgramWeek:       newProgramWeek(db, opts...),
		Session:           newSession(db, opts...),
		SessionExercise:   newSessionExercise(db, opts...),
		SetLog:            newSetLog(db, opts...),
		SetVideo:          newSetVideo(db, opts...),
		User:              newUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	CoachAthlete      coachAthlete
	Equipment         equipment
	Exercise          exercise
	ExerciseEquipment exerciseEquipment
	Program           program
	ProgramDay        programDay
	ProgramExercise   programExercise
	ProgramSet        programSet
	ProgramSetGroup   programSetGroup
	ProgramWeek       programWeek
	Session           session
	SessionExercise   sessionExercise
	SetLog            setLog
	SetVideo          setVideo
	User              user
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                db,
		CoachAthlete:      q.CoachAthlete.clone(db),
		Equipment:         q.Equipment.clone(db),
		Exercise:          q.Exercise.clone(db),
		ExerciseEquipment: q.ExerciseEquipment.clone(db),
		Program:           q.Program.clone(db),
		ProgramDay:        q.ProgramDay.clone(db),
		ProgramExercise:   q.ProgramExercise.clone(db),
		ProgramSet:        q.ProgramSet.clone(db),
		ProgramSetGroup:   q.ProgramSetGroup.clone(db),
		ProgramWeek:       q.ProgramWeek.clone(db),
		Session:           q.Session.clone(db),
		SessionExercise:   q.SessionExercise.clone(db),
		SetLog:            q.SetLog.clone(db),
		SetVideo:          q.SetVideo.clone(db),
		User:              q.User.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                db,
		CoachAthlete:      q.CoachAthlete.replaceDB(db),
		Equipment:         q.Equipment.replaceDB(db),
		Exercise:          q.Exercise.replaceDB(db),
		ExerciseEquipment: q.ExerciseEquipment.replaceDB(db),
		Program:           q.Program.replaceDB(db),
		ProgramDay:        q.ProgramDay.replaceDB(db),
		ProgramExercise:   q.ProgramExercise.replaceDB(db),
		ProgramSet:        q.ProgramSet.replaceDB(db),
		ProgramSetGroup:   q.ProgramSetGroup.replaceDB(db),
		ProgramWeek:       q.ProgramWeek.replaceDB(db),
		Session:           q.Session.replaceDB(db),
		SessionExercise:   q.SessionExercise.replaceDB(db),
		SetLog:            q.SetLog.replaceDB(db),
		SetVideo:          q.SetVideo.replaceDB(db),
		User:              q.User.replaceDB(db),
	}
}

type queryCtx struct {
	CoachAthlete      *coachAthleteDo
	Equipment         *equipmentDo
	Exercise          *exerciseDo
	ExerciseEquipment *exerciseEquipmentDo
	Program           *programDo
	ProgramDay        *programDayDo
	ProgramExercise   *programExerciseDo
	ProgramSet        *programSetDo
	ProgramSetGroup   *programSetGroupDo
	ProgramWeek       *programWeekDo
	Session           *sessionDo
	SessionExercise   *sessionExerciseDo
	SetLog            *setLogDo
	SetVideo          *setVideoDo
	User              *userDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		CoachAthlete:      q.CoachAthlete.WithContext(ctx),
		Equipment:         q.Equipment.WithContext(ctx),
		Exercise:          q.Exercise.WithContext(ctx),
		ExerciseEquipment: q.ExerciseEquipment.WithContext(ctx),
		Program:           q.Program.WithContext(ctx),
		ProgramDay:        q.ProgramDay.WithContext(ctx),
		ProgramExercise:   q.ProgramExercise.WithContext(ctx),
		ProgramSet:        q.ProgramSet.WithContext(ctx),
		ProgramSetGroup:   q.ProgramSetGroup.WithContext(ctx),
		ProgramWeek:       q.ProgramWeek.WithContext(ctx),
		Session:           q.Session.WithContext(ctx),
		SessionExercise:   q.SessionExercise.WithContext(ctx),
		SetLog:            q.SetLog.WithContext(ctx),
		SetVideo:          q.SetVideo.WithContext(ctx),
		User:              q.User.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
