// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/thompsonlogan/fitlytics/backend/internal/models/generated"
)

func newProgramSet(db *gorm.DB, opts ...gen.DOOption) programSet {
	_programSet := programSet{}

	_programSet.programSetDo.UseDB(db, opts...)
	_programSet.programSetDo.UseModel(&generated.ProgramSet{})

	tableName := _programSet.programSetDo.TableName()
	_programSet.ALL = field.NewAsterisk(tableName)
	_programSet.ID = field.NewField(tableName, "id")
	_programSet.GroupID = field.NewField(tableName, "group_id")
	_programSet.Sequence = field.NewInt32(tableName, "sequence")
	_programSet.SetType = field.NewString(tableName, "set_type")
	_programSet.RepsMin = field.NewInt32(tableName, "reps_min")
	_programSet.RepsMax = field.NewInt32(tableName, "reps_max")
	_programSet.IntensityText = field.NewString(tableName, "intensity_text")
	_programSet.PrescribedLoadKg = field.NewFloat64(tableName, "prescribed_load_kg")
	_programSet.PrescribedLoadModifier = field.NewString(tableName, "prescribed_load_modifier")
	_programSet.CapLoadKg = field.NewFloat64(tableName, "cap_load_kg")
	_programSet.PrescribedRpe = field.NewFloat64(tableName, "prescribed_rpe")
	_programSet.CreatedAt = field.NewTime(tableName, "created_at")
	_programSet.UpdatedAt = field.NewTime(tableName, "updated_at")

	_programSet.fillFieldMap()

	return _programSet
}

type programSet struct {
	programSetDo programSetDo

	ALL                    field.Asterisk
	ID                     field.Field
	GroupID                field.Field
	Sequence               field.Int32
	SetType                field.String
	RepsMin                field.Int32
	RepsMax                field.Int32
	IntensityText          field.String
	PrescribedLoadKg       field.Float64
	PrescribedLoadModifier field.String
	CapLoadKg              field.Float64
	PrescribedRpe          field.Float64
	CreatedAt              field.Time
	UpdatedAt              field.Time

	fieldMap map[string]field.Expr
}

func (p programSet) Table(newTableName string) *programSet {
	p.programSetDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p programSet) As(alias string) *programSet {
	p.programSetDo.DO = *(p.programSetDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *programSet) updateTableName(table string) *programSet {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewField(table, "id")
	p.GroupID = field.NewField(table, "group_id")
	p.Sequence = field.NewInt32(table, "sequence")
	p.SetType = field.NewString(table, "set_type")
	p.RepsMin = field.NewInt32(table, "reps_min")
	p.RepsMax = field.NewInt32(table, "reps_max")
	p.IntensityText = field.NewString(table, "intensity_text")
	p.PrescribedLoadKg = field.NewFloat64(table, "prescribed_load_kg")
	p.PrescribedLoadModifier = field.NewString(table, "prescribed_load_modifier")
	p.CapLoadKg = field.NewFloat64(table, "cap_load_kg")
	p.PrescribedRpe = field.NewFloat64(table, "prescribed_rpe")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")

	p.fillFieldMap()

	return p
}

func (p *programSet) WithContext(ctx context.Context) *programSetDo {
	return p.programSetDo.WithContext(ctx)
}

func (p programSet) TableName() string { return p.programSetDo.TableName() }

func (p programSet) Alias() string { return p.programSetDo.Alias() }

func (p programSet) Columns(cols ...field.Expr) gen.Columns { return p.programSetDo.Columns(cols...) }

func (p *programSet) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *programSet) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 13)
	p.fieldMap["id"] = p.ID
	p.fieldMap["group_id"] = p.GroupID
	p.fieldMap["sequence"] = p.Sequence
	p.fieldMap["set_type"] = p.SetType
	p.fieldMap["reps_min"] = p.RepsMin
	p.fieldMap["reps_max"] = p.RepsMax
	p.fieldMap["intensity_text"] = p.IntensityText
	p.fieldMap["prescribed_load_kg"] = p.PrescribedLoadKg
	p.fieldMap["prescribed_load_modifier"] = p.PrescribedLoadModifier
	p.fieldMap["cap_load_kg"] = p.CapLoadKg
	p.fieldMap["prescribed_rpe"] = p.PrescribedRpe
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
}

func (p programSet) clone(db *gorm.DB) programSet {
	p.programSetDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p programSet) replaceDB(db *gorm.DB) programSet {
	p.programSetDo.ReplaceDB(db)
	return p
}

type programSetDo struct{ gen.DO }

func (p programSetDo) Debug() *programSetDo {
	return p.withDO(p.DO.Debug())
}

func (p programSetDo) WithContext(ctx context.Context) *programSetDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p programSetDo) ReadDB() *programSetDo {
	return p.Clauses(dbresolver.Read)
}

func (p programSetDo) WriteDB() *programSetDo {
	return p.Clauses(dbresolver.Write)
}

func (p programSetDo) Session(config *gorm.Session) *programSetDo {
	return p.withDO(p.DO.Session(config))
}

func (p programSetDo) Clauses(conds ...clause.Expression) *programSetDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p programSetDo) Returning(value interface{}, columns ...string) *programSetDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p programSetDo) Not(conds ...gen.Condition) *programSetDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p programSetDo) Or(conds ...gen.Condition) *programSetDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p programSetDo) Select(conds ...field.Expr) *programSetDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p programSetDo) Where(conds ...gen.Condition) *programSetDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p programSetDo) Order(conds ...field.Expr) *programSetDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p programSetDo) Distinct(cols ...field.Expr) *programSetDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p programSetDo) Omit(cols ...field.Expr) *programSetDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p programSetDo) Join(table schema.Tabler, on ...field.Expr) *programSetDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p programSetDo) LeftJoin(table schema.Tabler, on ...field.Expr) *programSetDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p programSetDo) RightJoin(table schema.Tabler, on ...field.Expr) *programSetDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p programSetDo) Group(cols ...field.Expr) *programSetDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p programSetDo) Having(conds ...gen.Condition) *programSetDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p programSetDo) Limit(limit int) *programSetDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p programSetDo) Offset(offset int) *programSetDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p programSetDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *programSetDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p programSetDo) Unscoped() *programSetDo {
	return p.withDO(p.DO.Unscoped())
}

func (p programSetDo) Create(values ...*generated.ProgramSet) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p programSetDo) CreateInBatches(values []*generated.ProgramSet, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p programSetDo) Save(values ...*generated.ProgramSet) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p programSetDo) First() (*generated.ProgramSet, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*generated.ProgramSet), nil
	}
}

func (p programSetDo) Take() (*generated.ProgramSet, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*generated.ProgramSet), nil
	}
}

func (p programSetDo) Last() (*generated.ProgramSet, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*generated.ProgramSet), nil
	}
}

func (p programSetDo) Find() ([]*generated.ProgramSet, error) {
	result, err := p.DO.Find()
	return result.([]*generated.ProgramSet), err
}

func (p programSetDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*generated.ProgramSet, err error) {
	buf := make([]*generated.ProgramSet, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p programSetDo) FindInBatches(result *[]*generated.ProgramSet, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p programSetDo) Attrs(attrs ...field.AssignExpr) *programSetDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p programSetDo) Assign(attrs ...field.AssignExpr) *programSetDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p programSetDo) Joins(fields ...field.RelationField) *programSetDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p programSetDo) Preload(fields ...field.RelationField) *programSetDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p programSetDo) FirstOrInit() (*generated.ProgramSet, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*generated.ProgramSet), nil
	}
}

func (p programSetDo) FirstOrCreate() (*generated.ProgramSet, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*generated.ProgramSet), nil
	}
}

func (p programSetDo) FindByPage(offset int, limit int) (result []*generated.ProgramSet, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p programSetDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p programSetDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p programSetDo) Delete(models ...*generated.ProgramSet) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *programSetDo) withDO(do gen.Dao) *programSetDo {
	p.DO = *do.(*gen.DO)
	return p
}
