// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/thompsonlogan/fitlytics/backend/internal/models/generated"
)

func newProgramBlock(db *gorm.DB, opts ...gen.DOOption) programBlock {
	_programBlock := programBlock{}

	_programBlock.programBlockDo.UseDB(db, opts...)
	_programBlock.programBlockDo.UseModel(&generated.ProgramBlock{})

	tableName := _programBlock.programBlockDo.TableName()
	_programBlock.ALL = field.NewAsterisk(tableName)
	_programBlock.ID = field.NewField(tableName, "id")
	_programBlock.ProgramID = field.NewField(tableName, "program_id")
	_programBlock.Sequence = field.NewInt32(tableName, "sequence")
	_programBlock.Name = field.NewString(tableName, "name")
	_programBlock.CreatedAt = field.NewTime(tableName, "created_at")
	_programBlock.UpdatedAt = field.NewTime(tableName, "updated_at")

	_programBlock.fillFieldMap()

	return _programBlock
}

type programBlock struct {
	programBlockDo programBlockDo

	ALL       field.Asterisk
	ID        field.Field
	ProgramID field.Field
	Sequence  field.Int32
	Name      field.String
	CreatedAt field.Time
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

func (p programBlock) Table(newTableName string) *programBlock {
	p.programBlockDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p programBlock) As(alias string) *programBlock {
	p.programBlockDo.DO = *(p.programBlockDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *programBlock) updateTableName(table string) *programBlock {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewField(table, "id")
	p.ProgramID = field.NewField(table, "program_id")
	p.Sequence = field.NewInt32(table, "sequence")
	p.Name = field.NewString(table, "name")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")

	p.fillFieldMap()

	return p
}

func (p *programBlock) WithContext(ctx context.Context) *programBlockDo {
	return p.programBlockDo.WithContext(ctx)
}

func (p programBlock) TableName() string { return p.programBlockDo.TableName() }

func (p programBlock) Alias() string { return p.programBlockDo.Alias() }

func (p programBlock) Columns(cols ...field.Expr) gen.Columns {
	return p.programBlockDo.Columns(cols...)
}

func (p *programBlock) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *programBlock) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 6)
	p.fieldMap["id"] = p.ID
	p.fieldMap["program_id"] = p.ProgramID
	p.fieldMap["sequence"] = p.Sequence
	p.fieldMap["name"] = p.Name
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
}

func (p programBlock) clone(db *gorm.DB) programBlock {
	p.programBlockDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p programBlock) replaceDB(db *gorm.DB) programBlock {
	p.programBlockDo.ReplaceDB(db)
	return p
}

type programBlockDo struct{ gen.DO }

func (p programBlockDo) Debug() *programBlockDo {
	return p.withDO(p.DO.Debug())
}

func (p programBlockDo) WithContext(ctx context.Context) *programBlockDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p programBlockDo) ReadDB() *programBlockDo {
	return p.Clauses(dbresolver.Read)
}

func (p programBlockDo) WriteDB() *programBlockDo {
	return p.Clauses(dbresolver.Write)
}

func (p programBlockDo) Session(config *gorm.Session) *programBlockDo {
	return p.withDO(p.DO.Session(config))
}

func (p programBlockDo) Clauses(conds ...clause.Expression) *programBlockDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p programBlockDo) Returning(value interface{}, columns ...string) *programBlockDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p programBlockDo) Not(conds ...gen.Condition) *programBlockDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p programBlockDo) Or(conds ...gen.Condition) *programBlockDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p programBlockDo) Select(conds ...field.Expr) *programBlockDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p programBlockDo) Where(conds ...gen.Condition) *programBlockDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p programBlockDo) Order(conds ...field.Expr) *programBlockDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p programBlockDo) Distinct(cols ...field.Expr) *programBlockDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p programBlockDo) Omit(cols ...field.Expr) *programBlockDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p programBlockDo) Join(table schema.Tabler, on ...field.Expr) *programBlockDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p programBlockDo) LeftJoin(table schema.Tabler, on ...field.Expr) *programBlockDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p programBlockDo) RightJoin(table schema.Tabler, on ...field.Expr) *programBlockDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p programBlockDo) Group(cols ...field.Expr) *programBlockDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p programBlockDo) Having(conds ...gen.Condition) *programBlockDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p programBlockDo) Limit(limit int) *programBlockDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p programBlockDo) Offset(offset int) *programBlockDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p programBlockDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *programBlockDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p programBlockDo) Unscoped() *programBlockDo {
	return p.withDO(p.DO.Unscoped())
}

func (p programBlockDo) Create(values ...*generated.ProgramBlock) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p programBlockDo) CreateInBatches(values []*generated.ProgramBlock, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p programBlockDo) Save(values ...*generated.ProgramBlock) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p programBlockDo) First() (*generated.ProgramBlock, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*generated.ProgramBlock), nil
	}
}

func (p programBlockDo) Take() (*generated.ProgramBlock, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*generated.ProgramBlock), nil
	}
}

func (p programBlockDo) Last() (*generated.ProgramBlock, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*generated.ProgramBlock), nil
	}
}

func (p programBlockDo) Find() ([]*generated.ProgramBlock, error) {
	result, err := p.DO.Find()
	return result.([]*generated.ProgramBlock), err
}

func (p programBlockDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*generated.ProgramBlock, err error) {
	buf := make([]*generated.ProgramBlock, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p programBlockDo) FindInBatches(result *[]*generated.ProgramBlock, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p programBlockDo) Attrs(attrs ...field.AssignExpr) *programBlockDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p programBlockDo) Assign(attrs ...field.AssignExpr) *programBlockDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p programBlockDo) Joins(fields ...field.RelationField) *programBlockDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p programBlockDo) Preload(fields ...field.RelationField) *programBlockDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p programBlockDo) FirstOrInit() (*generated.ProgramBlock, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*generated.ProgramBlock), nil
	}
}

func (p programBlockDo) FirstOrCreate() (*generated.ProgramBlock, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*generated.ProgramBlock), nil
	}
}

func (p programBlockDo) FindByPage(offset int, limit int) (result []*generated.ProgramBlock, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p programBlockDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p programBlockDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p programBlockDo) Delete(models ...*generated.ProgramBlock) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *programBlockDo) withDO(do gen.Dao) *programBlockDo {
	p.DO = *do.(*gen.DO)
	return p
}
