// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/thompsonlogan/fitlytics/backend/internal/models/generated"
)

func newProgram(db *gorm.DB, opts ...gen.DOOption) program {
	_program := program{}

	_program.programDo.UseDB(db, opts...)
	_program.programDo.UseModel(&generated.Program{})

	tableName := _program.programDo.TableName()
	_program.ALL = field.NewAsterisk(tableName)
	_program.ID = field.NewField(tableName, "id")
	_program.OwnerUserID = field.NewField(tableName, "owner_user_id")
	_program.Name = field.NewString(tableName, "name")
	_program.Description = field.NewString(tableName, "description")
	_program.StartDate = field.NewTime(tableName, "start_date")
	_program.CreatedAt = field.NewTime(tableName, "created_at")
	_program.UpdatedAt = field.NewTime(tableName, "updated_at")
	_program.DeletedAt = field.NewField(tableName, "deleted_at")
	_program.Weeks = programHasManyWeeks{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Weeks", "generated.ProgramWeek"),
		Days: struct {
			field.RelationField
			Exercises struct {
				field.RelationField
				SetTargets struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("Weeks.Days", "generated.ProgramDay"),
			Exercises: struct {
				field.RelationField
				SetTargets struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Weeks.Days.Exercises", "generated.ProgramExercise"),
				SetTargets: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Weeks.Days.Exercises.SetTargets", "generated.ProgramSetTarget"),
				},
			},
		},
	}

	_program.fillFieldMap()

	return _program
}

type program struct {
	programDo programDo

	ALL         field.Asterisk
	ID          field.Field
	OwnerUserID field.Field
	Name        field.String
	Description field.String
	StartDate   field.Time
	CreatedAt   field.Time
	UpdatedAt   field.Time
	DeletedAt   field.Field
	Weeks       programHasManyWeeks

	fieldMap map[string]field.Expr
}

func (p program) Table(newTableName string) *program {
	p.programDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p program) As(alias string) *program {
	p.programDo.DO = *(p.programDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *program) updateTableName(table string) *program {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewField(table, "id")
	p.OwnerUserID = field.NewField(table, "owner_user_id")
	p.Name = field.NewString(table, "name")
	p.Description = field.NewString(table, "description")
	p.StartDate = field.NewTime(table, "start_date")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")
	p.DeletedAt = field.NewField(table, "deleted_at")

	p.fillFieldMap()

	return p
}

func (p *program) WithContext(ctx context.Context) *programDo { return p.programDo.WithContext(ctx) }

func (p program) TableName() string { return p.programDo.TableName() }

func (p program) Alias() string { return p.programDo.Alias() }

func (p program) Columns(cols ...field.Expr) gen.Columns { return p.programDo.Columns(cols...) }

func (p *program) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *program) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 9)
	p.fieldMap["id"] = p.ID
	p.fieldMap["owner_user_id"] = p.OwnerUserID
	p.fieldMap["name"] = p.Name
	p.fieldMap["description"] = p.Description
	p.fieldMap["start_date"] = p.StartDate
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
	p.fieldMap["deleted_at"] = p.DeletedAt

}

func (p program) clone(db *gorm.DB) program {
	p.programDo.ReplaceConnPool(db.Statement.ConnPool)
	p.Weeks.db = db.Session(&gorm.Session{Initialized: true})
	p.Weeks.db.Statement.ConnPool = db.Statement.ConnPool
	return p
}

func (p program) replaceDB(db *gorm.DB) program {
	p.programDo.ReplaceDB(db)
	p.Weeks.db = db.Session(&gorm.Session{})
	return p
}

type programHasManyWeeks struct {
	db *gorm.DB

	field.RelationField

	Days struct {
		field.RelationField
		Exercises struct {
			field.RelationField
			SetTargets struct {
				field.RelationField
			}
		}
	}
}

func (a programHasManyWeeks) Where(conds ...field.Expr) *programHasManyWeeks {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a programHasManyWeeks) WithContext(ctx context.Context) *programHasManyWeeks {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a programHasManyWeeks) Session(session *gorm.Session) *programHasManyWeeks {
	a.db = a.db.Session(session)
	return &a
}

func (a programHasManyWeeks) Model(m *generated.Program) *programHasManyWeeksTx {
	return &programHasManyWeeksTx{a.db.Model(m).Association(a.Name())}
}

func (a programHasManyWeeks) Unscoped() *programHasManyWeeks {
	a.db = a.db.Unscoped()
	return &a
}

type programHasManyWeeksTx struct{ tx *gorm.Association }

func (a programHasManyWeeksTx) Find() (result []*generated.ProgramWeek, err error) {
	return result, a.tx.Find(&result)
}

func (a programHasManyWeeksTx) Append(values ...*generated.ProgramWeek) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a programHasManyWeeksTx) Replace(values ...*generated.ProgramWeek) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a programHasManyWeeksTx) Delete(values ...*generated.ProgramWeek) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a programHasManyWeeksTx) Clear() error {
	return a.tx.Clear()
}

func (a programHasManyWeeksTx) Count() int64 {
	return a.tx.Count()
}

func (a programHasManyWeeksTx) Unscoped() *programHasManyWeeksTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type programDo struct{ gen.DO }

func (p programDo) Debug() *programDo {
	return p.withDO(p.DO.Debug())
}

func (p programDo) WithContext(ctx context.Context) *programDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p programDo) ReadDB() *programDo {
	return p.Clauses(dbresolver.Read)
}

func (p programDo) WriteDB() *programDo {
	return p.Clauses(dbresolver.Write)
}

func (p programDo) Session(config *gorm.Session) *programDo {
	return p.withDO(p.DO.Session(config))
}

func (p programDo) Clauses(conds ...clause.Expression) *programDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p programDo) Returning(value interface{}, columns ...string) *programDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p programDo) Not(conds ...gen.Condition) *programDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p programDo) Or(conds ...gen.Condition) *programDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p programDo) Select(conds ...field.Expr) *programDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p programDo) Where(conds ...gen.Condition) *programDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p programDo) Order(conds ...field.Expr) *programDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p programDo) Distinct(cols ...field.Expr) *programDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p programDo) Omit(cols ...field.Expr) *programDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p programDo) Join(table schema.Tabler, on ...field.Expr) *programDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p programDo) LeftJoin(table schema.Tabler, on ...field.Expr) *programDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p programDo) RightJoin(table schema.Tabler, on ...field.Expr) *programDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p programDo) Group(cols ...field.Expr) *programDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p programDo) Having(conds ...gen.Condition) *programDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p programDo) Limit(limit int) *programDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p programDo) Offset(offset int) *programDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p programDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *programDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p programDo) Unscoped() *programDo {
	return p.withDO(p.DO.Unscoped())
}

func (p programDo) Create(values ...*generated.Program) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p programDo) CreateInBatches(values []*generated.Program, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p programDo) Save(values ...*generated.Program) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p programDo) First() (*generated.Program, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*generated.Program), nil
	}
}

func (p programDo) Take() (*generated.Program, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*generated.Program), nil
	}
}

func (p programDo) Last() (*generated.Program, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*generated.Program), nil
	}
}

func (p programDo) Find() ([]*generated.Program, error) {
	result, err := p.DO.Find()
	return result.([]*generated.Program), err
}

func (p programDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*generated.Program, err error) {
	buf := make([]*generated.Program, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p programDo) FindInBatches(result *[]*generated.Program, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p programDo) Attrs(attrs ...field.AssignExpr) *programDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p programDo) Assign(attrs ...field.AssignExpr) *programDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p programDo) Joins(fields ...field.RelationField) *programDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p programDo) Preload(fields ...field.RelationField) *programDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p programDo) FirstOrInit() (*generated.Program, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*generated.Program), nil
	}
}

func (p programDo) FirstOrCreate() (*generated.Program, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*generated.Program), nil
	}
}

func (p programDo) FindByPage(offset int, limit int) (result []*generated.Program, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p programDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p programDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p programDo) Delete(models ...*generated.Program) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *programDo) withDO(do gen.Dao) *programDo {
	p.DO = *do.(*gen.DO)
	return p
}
