// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/thompsonlogan/fitlytics/backend/internal/models/generated"
)

func newProgramExercise(db *gorm.DB, opts ...gen.DOOption) programExercise {
	_programExercise := programExercise{}

	_programExercise.programExerciseDo.UseDB(db, opts...)
	_programExercise.programExerciseDo.UseModel(&generated.ProgramExercise{})

	tableName := _programExercise.programExerciseDo.TableName()
	_programExercise.ALL = field.NewAsterisk(tableName)
	_programExercise.ID = field.NewField(tableName, "id")
	_programExercise.ProgramDayID = field.NewField(tableName, "program_day_id")
	_programExercise.Sequence = field.NewInt32(tableName, "sequence")
	_programExercise.ExerciseID = field.NewField(tableName, "exercise_id")
	_programExercise.SubText = field.NewString(tableName, "sub_text")
	_programExercise.RestSeconds = field.NewInt32(tableName, "rest_seconds")
	_programExercise.CreatedAt = field.NewTime(tableName, "created_at")
	_programExercise.UpdatedAt = field.NewTime(tableName, "updated_at")
	_programExercise.Groups = programExerciseHasManyGroups{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Groups", "generated.ProgramSetGroup"),
		Sets: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Groups.Sets", "generated.ProgramSet"),
		},
	}

	_programExercise.fillFieldMap()

	return _programExercise
}

type programExercise struct {
	programExerciseDo programExerciseDo

	ALL          field.Asterisk
	ID           field.Field
	ProgramDayID field.Field
	Sequence     field.Int32
	ExerciseID   field.Field
	SubText      field.String
	RestSeconds  field.Int32
	CreatedAt    field.Time
	UpdatedAt    field.Time
	Groups       programExerciseHasManyGroups

	fieldMap map[string]field.Expr
}

func (p programExercise) Table(newTableName string) *programExercise {
	p.programExerciseDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p programExercise) As(alias string) *programExercise {
	p.programExerciseDo.DO = *(p.programExerciseDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *programExercise) updateTableName(table string) *programExercise {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewField(table, "id")
	p.ProgramDayID = field.NewField(table, "program_day_id")
	p.Sequence = field.NewInt32(table, "sequence")
	p.ExerciseID = field.NewField(table, "exercise_id")
	p.SubText = field.NewString(table, "sub_text")
	p.RestSeconds = field.NewInt32(table, "rest_seconds")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")

	p.fillFieldMap()

	return p
}

func (p *programExercise) WithContext(ctx context.Context) *programExerciseDo {
	return p.programExerciseDo.WithContext(ctx)
}

func (p programExercise) TableName() string { return p.programExerciseDo.TableName() }

func (p programExercise) Alias() string { return p.programExerciseDo.Alias() }

func (p programExercise) Columns(cols ...field.Expr) gen.Columns {
	return p.programExerciseDo.Columns(cols...)
}

func (p *programExercise) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *programExercise) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 9)
	p.fieldMap["id"] = p.ID
	p.fieldMap["program_day_id"] = p.ProgramDayID
	p.fieldMap["sequence"] = p.Sequence
	p.fieldMap["exercise_id"] = p.ExerciseID
	p.fieldMap["sub_text"] = p.SubText
	p.fieldMap["rest_seconds"] = p.RestSeconds
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt

}

func (p programExercise) clone(db *gorm.DB) programExercise {
	p.programExerciseDo.ReplaceConnPool(db.Statement.ConnPool)
	p.Groups.db = db.Session(&gorm.Session{Initialized: true})
	p.Groups.db.Statement.ConnPool = db.Statement.ConnPool
	return p
}

func (p programExercise) replaceDB(db *gorm.DB) programExercise {
	p.programExerciseDo.ReplaceDB(db)
	p.Groups.db = db.Session(&gorm.Session{})
	return p
}

type programExerciseHasManyGroups struct {
	db *gorm.DB

	field.RelationField

	Sets struct {
		field.RelationField
	}
}

func (a programExerciseHasManyGroups) Where(conds ...field.Expr) *programExerciseHasManyGroups {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a programExerciseHasManyGroups) WithContext(ctx context.Context) *programExerciseHasManyGroups {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a programExerciseHasManyGroups) Session(session *gorm.Session) *programExerciseHasManyGroups {
	a.db = a.db.Session(session)
	return &a
}

func (a programExerciseHasManyGroups) Model(m *generated.ProgramExercise) *programExerciseHasManyGroupsTx {
	return &programExerciseHasManyGroupsTx{a.db.Model(m).Association(a.Name())}
}

func (a programExerciseHasManyGroups) Unscoped() *programExerciseHasManyGroups {
	a.db = a.db.Unscoped()
	return &a
}

type programExerciseHasManyGroupsTx struct{ tx *gorm.Association }

func (a programExerciseHasManyGroupsTx) Find() (result []*generated.ProgramSetGroup, err error) {
	return result, a.tx.Find(&result)
}

func (a programExerciseHasManyGroupsTx) Append(values ...*generated.ProgramSetGroup) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a programExerciseHasManyGroupsTx) Replace(values ...*generated.ProgramSetGroup) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a programExerciseHasManyGroupsTx) Delete(values ...*generated.ProgramSetGroup) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a programExerciseHasManyGroupsTx) Clear() error {
	return a.tx.Clear()
}

func (a programExerciseHasManyGroupsTx) Count() int64 {
	return a.tx.Count()
}

func (a programExerciseHasManyGroupsTx) Unscoped() *programExerciseHasManyGroupsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type programExerciseDo struct{ gen.DO }

func (p programExerciseDo) Debug() *programExerciseDo {
	return p.withDO(p.DO.Debug())
}

func (p programExerciseDo) WithContext(ctx context.Context) *programExerciseDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p programExerciseDo) ReadDB() *programExerciseDo {
	return p.Clauses(dbresolver.Read)
}

func (p programExerciseDo) WriteDB() *programExerciseDo {
	return p.Clauses(dbresolver.Write)
}

func (p programExerciseDo) Session(config *gorm.Session) *programExerciseDo {
	return p.withDO(p.DO.Session(config))
}

func (p programExerciseDo) Clauses(conds ...clause.Expression) *programExerciseDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p programExerciseDo) Returning(value interface{}, columns ...string) *programExerciseDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p programExerciseDo) Not(conds ...gen.Condition) *programExerciseDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p programExerciseDo) Or(conds ...gen.Condition) *programExerciseDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p programExerciseDo) Select(conds ...field.Expr) *programExerciseDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p programExerciseDo) Where(conds ...gen.Condition) *programExerciseDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p programExerciseDo) Order(conds ...field.Expr) *programExerciseDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p programExerciseDo) Distinct(cols ...field.Expr) *programExerciseDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p programExerciseDo) Omit(cols ...field.Expr) *programExerciseDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p programExerciseDo) Join(table schema.Tabler, on ...field.Expr) *programExerciseDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p programExerciseDo) LeftJoin(table schema.Tabler, on ...field.Expr) *programExerciseDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p programExerciseDo) RightJoin(table schema.Tabler, on ...field.Expr) *programExerciseDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p programExerciseDo) Group(cols ...field.Expr) *programExerciseDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p programExerciseDo) Having(conds ...gen.Condition) *programExerciseDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p programExerciseDo) Limit(limit int) *programExerciseDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p programExerciseDo) Offset(offset int) *programExerciseDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p programExerciseDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *programExerciseDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p programExerciseDo) Unscoped() *programExerciseDo {
	return p.withDO(p.DO.Unscoped())
}

func (p programExerciseDo) Create(values ...*generated.ProgramExercise) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p programExerciseDo) CreateInBatches(values []*generated.ProgramExercise, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p programExerciseDo) Save(values ...*generated.ProgramExercise) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p programExerciseDo) First() (*generated.ProgramExercise, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*generated.ProgramExercise), nil
	}
}

func (p programExerciseDo) Take() (*generated.ProgramExercise, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*generated.ProgramExercise), nil
	}
}

func (p programExerciseDo) Last() (*generated.ProgramExercise, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*generated.ProgramExercise), nil
	}
}

func (p programExerciseDo) Find() ([]*generated.ProgramExercise, error) {
	result, err := p.DO.Find()
	return result.([]*generated.ProgramExercise), err
}

func (p programExerciseDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*generated.ProgramExercise, err error) {
	buf := make([]*generated.ProgramExercise, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p programExerciseDo) FindInBatches(result *[]*generated.ProgramExercise, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p programExerciseDo) Attrs(attrs ...field.AssignExpr) *programExerciseDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p programExerciseDo) Assign(attrs ...field.AssignExpr) *programExerciseDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p programExerciseDo) Joins(fields ...field.RelationField) *programExerciseDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p programExerciseDo) Preload(fields ...field.RelationField) *programExerciseDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p programExerciseDo) FirstOrInit() (*generated.ProgramExercise, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*generated.ProgramExercise), nil
	}
}

func (p programExerciseDo) FirstOrCreate() (*generated.ProgramExercise, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*generated.ProgramExercise), nil
	}
}

func (p programExerciseDo) FindByPage(offset int, limit int) (result []*generated.ProgramExercise, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p programExerciseDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p programExerciseDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p programExerciseDo) Delete(models ...*generated.ProgramExercise) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *programExerciseDo) withDO(do gen.Dao) *programExerciseDo {
	p.DO = *do.(*gen.DO)
	return p
}
