// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/thompsonlogan/fitlytics/backend/internal/models/generated"
)

func newProgramSetTarget(db *gorm.DB, opts ...gen.DOOption) programSetTarget {
	_programSetTarget := programSetTarget{}

	_programSetTarget.programSetTargetDo.UseDB(db, opts...)
	_programSetTarget.programSetTargetDo.UseModel(&generated.ProgramSetTarget{})

	tableName := _programSetTarget.programSetTargetDo.TableName()
	_programSetTarget.ALL = field.NewAsterisk(tableName)
	_programSetTarget.ID = field.NewField(tableName, "id")
	_programSetTarget.ProgramExerciseID = field.NewField(tableName, "program_exercise_id")
	_programSetTarget.Sequence = field.NewInt32(tableName, "sequence")
	_programSetTarget.SetType = field.NewString(tableName, "set_type")
	_programSetTarget.SetsCount = field.NewInt32(tableName, "sets_count")
	_programSetTarget.RepsMin = field.NewInt32(tableName, "reps_min")
	_programSetTarget.RepsMax = field.NewInt32(tableName, "reps_max")
	_programSetTarget.DurationTargetSec = field.NewInt32(tableName, "duration_target_sec")
	_programSetTarget.DistanceTargetM = field.NewFloat64(tableName, "distance_target_m")
	_programSetTarget.IntensityText = field.NewString(tableName, "intensity_text")
	_programSetTarget.PrescribedLoadKg = field.NewFloat64(tableName, "prescribed_load_kg")
	_programSetTarget.PrescribedLoadModifier = field.NewString(tableName, "prescribed_load_modifier")
	_programSetTarget.CapLoadKg = field.NewFloat64(tableName, "cap_load_kg")
	_programSetTarget.PrescribedRpe = field.NewFloat64(tableName, "prescribed_rpe")
	_programSetTarget.Notes = field.NewString(tableName, "notes")
	_programSetTarget.CreatedAt = field.NewTime(tableName, "created_at")
	_programSetTarget.UpdatedAt = field.NewTime(tableName, "updated_at")

	_programSetTarget.fillFieldMap()

	return _programSetTarget
}

type programSetTarget struct {
	programSetTargetDo programSetTargetDo

	ALL                    field.Asterisk
	ID                     field.Field
	ProgramExerciseID      field.Field
	Sequence               field.Int32
	SetType                field.String
	SetsCount              field.Int32
	RepsMin                field.Int32
	RepsMax                field.Int32
	DurationTargetSec      field.Int32
	DistanceTargetM        field.Float64
	IntensityText          field.String
	PrescribedLoadKg       field.Float64
	PrescribedLoadModifier field.String
	CapLoadKg              field.Float64
	PrescribedRpe          field.Float64
	Notes                  field.String
	CreatedAt              field.Time
	UpdatedAt              field.Time

	fieldMap map[string]field.Expr
}

func (p programSetTarget) Table(newTableName string) *programSetTarget {
	p.programSetTargetDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p programSetTarget) As(alias string) *programSetTarget {
	p.programSetTargetDo.DO = *(p.programSetTargetDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *programSetTarget) updateTableName(table string) *programSetTarget {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewField(table, "id")
	p.ProgramExerciseID = field.NewField(table, "program_exercise_id")
	p.Sequence = field.NewInt32(table, "sequence")
	p.SetType = field.NewString(table, "set_type")
	p.SetsCount = field.NewInt32(table, "sets_count")
	p.RepsMin = field.NewInt32(table, "reps_min")
	p.RepsMax = field.NewInt32(table, "reps_max")
	p.DurationTargetSec = field.NewInt32(table, "duration_target_sec")
	p.DistanceTargetM = field.NewFloat64(table, "distance_target_m")
	p.IntensityText = field.NewString(table, "intensity_text")
	p.PrescribedLoadKg = field.NewFloat64(table, "prescribed_load_kg")
	p.PrescribedLoadModifier = field.NewString(table, "prescribed_load_modifier")
	p.CapLoadKg = field.NewFloat64(table, "cap_load_kg")
	p.PrescribedRpe = field.NewFloat64(table, "prescribed_rpe")
	p.Notes = field.NewString(table, "notes")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")

	p.fillFieldMap()

	return p
}

func (p *programSetTarget) WithContext(ctx context.Context) *programSetTargetDo {
	return p.programSetTargetDo.WithContext(ctx)
}

func (p programSetTarget) TableName() string { return p.programSetTargetDo.TableName() }

func (p programSetTarget) Alias() string { return p.programSetTargetDo.Alias() }

func (p programSetTarget) Columns(cols ...field.Expr) gen.Columns {
	return p.programSetTargetDo.Columns(cols...)
}

func (p *programSetTarget) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *programSetTarget) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 17)
	p.fieldMap["id"] = p.ID
	p.fieldMap["program_exercise_id"] = p.ProgramExerciseID
	p.fieldMap["sequence"] = p.Sequence
	p.fieldMap["set_type"] = p.SetType
	p.fieldMap["sets_count"] = p.SetsCount
	p.fieldMap["reps_min"] = p.RepsMin
	p.fieldMap["reps_max"] = p.RepsMax
	p.fieldMap["duration_target_sec"] = p.DurationTargetSec
	p.fieldMap["distance_target_m"] = p.DistanceTargetM
	p.fieldMap["intensity_text"] = p.IntensityText
	p.fieldMap["prescribed_load_kg"] = p.PrescribedLoadKg
	p.fieldMap["prescribed_load_modifier"] = p.PrescribedLoadModifier
	p.fieldMap["cap_load_kg"] = p.CapLoadKg
	p.fieldMap["prescribed_rpe"] = p.PrescribedRpe
	p.fieldMap["notes"] = p.Notes
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
}

func (p programSetTarget) clone(db *gorm.DB) programSetTarget {
	p.programSetTargetDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p programSetTarget) replaceDB(db *gorm.DB) programSetTarget {
	p.programSetTargetDo.ReplaceDB(db)
	return p
}

type programSetTargetDo struct{ gen.DO }

func (p programSetTargetDo) Debug() *programSetTargetDo {
	return p.withDO(p.DO.Debug())
}

func (p programSetTargetDo) WithContext(ctx context.Context) *programSetTargetDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p programSetTargetDo) ReadDB() *programSetTargetDo {
	return p.Clauses(dbresolver.Read)
}

func (p programSetTargetDo) WriteDB() *programSetTargetDo {
	return p.Clauses(dbresolver.Write)
}

func (p programSetTargetDo) Session(config *gorm.Session) *programSetTargetDo {
	return p.withDO(p.DO.Session(config))
}

func (p programSetTargetDo) Clauses(conds ...clause.Expression) *programSetTargetDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p programSetTargetDo) Returning(value interface{}, columns ...string) *programSetTargetDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p programSetTargetDo) Not(conds ...gen.Condition) *programSetTargetDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p programSetTargetDo) Or(conds ...gen.Condition) *programSetTargetDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p programSetTargetDo) Select(conds ...field.Expr) *programSetTargetDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p programSetTargetDo) Where(conds ...gen.Condition) *programSetTargetDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p programSetTargetDo) Order(conds ...field.Expr) *programSetTargetDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p programSetTargetDo) Distinct(cols ...field.Expr) *programSetTargetDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p programSetTargetDo) Omit(cols ...field.Expr) *programSetTargetDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p programSetTargetDo) Join(table schema.Tabler, on ...field.Expr) *programSetTargetDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p programSetTargetDo) LeftJoin(table schema.Tabler, on ...field.Expr) *programSetTargetDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p programSetTargetDo) RightJoin(table schema.Tabler, on ...field.Expr) *programSetTargetDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p programSetTargetDo) Group(cols ...field.Expr) *programSetTargetDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p programSetTargetDo) Having(conds ...gen.Condition) *programSetTargetDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p programSetTargetDo) Limit(limit int) *programSetTargetDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p programSetTargetDo) Offset(offset int) *programSetTargetDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p programSetTargetDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *programSetTargetDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p programSetTargetDo) Unscoped() *programSetTargetDo {
	return p.withDO(p.DO.Unscoped())
}

func (p programSetTargetDo) Create(values ...*generated.ProgramSetTarget) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p programSetTargetDo) CreateInBatches(values []*generated.ProgramSetTarget, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p programSetTargetDo) Save(values ...*generated.ProgramSetTarget) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p programSetTargetDo) First() (*generated.ProgramSetTarget, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*generated.ProgramSetTarget), nil
	}
}

func (p programSetTargetDo) Take() (*generated.ProgramSetTarget, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*generated.ProgramSetTarget), nil
	}
}

func (p programSetTargetDo) Last() (*generated.ProgramSetTarget, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*generated.ProgramSetTarget), nil
	}
}

func (p programSetTargetDo) Find() ([]*generated.ProgramSetTarget, error) {
	result, err := p.DO.Find()
	return result.([]*generated.ProgramSetTarget), err
}

func (p programSetTargetDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*generated.ProgramSetTarget, err error) {
	buf := make([]*generated.ProgramSetTarget, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p programSetTargetDo) FindInBatches(result *[]*generated.ProgramSetTarget, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p programSetTargetDo) Attrs(attrs ...field.AssignExpr) *programSetTargetDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p programSetTargetDo) Assign(attrs ...field.AssignExpr) *programSetTargetDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p programSetTargetDo) Joins(fields ...field.RelationField) *programSetTargetDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p programSetTargetDo) Preload(fields ...field.RelationField) *programSetTargetDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p programSetTargetDo) FirstOrInit() (*generated.ProgramSetTarget, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*generated.ProgramSetTarget), nil
	}
}

func (p programSetTargetDo) FirstOrCreate() (*generated.ProgramSetTarget, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*generated.ProgramSetTarget), nil
	}
}

func (p programSetTargetDo) FindByPage(offset int, limit int) (result []*generated.ProgramSetTarget, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p programSetTargetDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p programSetTargetDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p programSetTargetDo) Delete(models ...*generated.ProgramSetTarget) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *programSetTargetDo) withDO(do gen.Dao) *programSetTargetDo {
	p.DO = *do.(*gen.DO)
	return p
}
