// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/thompsonlogan/fitlytics/backend/internal/models/generated"
)

func newProgramWeek(db *gorm.DB, opts ...gen.DOOption) programWeek {
	_programWeek := programWeek{}

	_programWeek.programWeekDo.UseDB(db, opts...)
	_programWeek.programWeekDo.UseModel(&generated.ProgramWeek{})

	tableName := _programWeek.programWeekDo.TableName()
	_programWeek.ALL = field.NewAsterisk(tableName)
	_programWeek.ID = field.NewField(tableName, "id")
	_programWeek.ProgramID = field.NewField(tableName, "program_id")
	_programWeek.Sequence = field.NewInt32(tableName, "sequence")
	_programWeek.Name = field.NewString(tableName, "name")
	_programWeek.CreatedAt = field.NewTime(tableName, "created_at")
	_programWeek.UpdatedAt = field.NewTime(tableName, "updated_at")
	_programWeek.Days = programWeekHasManyDays{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Days", "generated.ProgramDay"),
		Exercises: struct {
			field.RelationField
			Groups struct {
				field.RelationField
				Sets struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("Days.Exercises", "generated.ProgramExercise"),
			Groups: struct {
				field.RelationField
				Sets struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Days.Exercises.Groups", "generated.ProgramSetGroup"),
				Sets: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Days.Exercises.Groups.Sets", "generated.ProgramSet"),
				},
			},
		},
	}

	_programWeek.fillFieldMap()

	return _programWeek
}

type programWeek struct {
	programWeekDo programWeekDo

	ALL       field.Asterisk
	ID        field.Field
	ProgramID field.Field
	Sequence  field.Int32
	Name      field.String
	CreatedAt field.Time
	UpdatedAt field.Time
	Days      programWeekHasManyDays

	fieldMap map[string]field.Expr
}

func (p programWeek) Table(newTableName string) *programWeek {
	p.programWeekDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p programWeek) As(alias string) *programWeek {
	p.programWeekDo.DO = *(p.programWeekDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *programWeek) updateTableName(table string) *programWeek {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewField(table, "id")
	p.ProgramID = field.NewField(table, "program_id")
	p.Sequence = field.NewInt32(table, "sequence")
	p.Name = field.NewString(table, "name")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")

	p.fillFieldMap()

	return p
}

func (p *programWeek) WithContext(ctx context.Context) *programWeekDo {
	return p.programWeekDo.WithContext(ctx)
}

func (p programWeek) TableName() string { return p.programWeekDo.TableName() }

func (p programWeek) Alias() string { return p.programWeekDo.Alias() }

func (p programWeek) Columns(cols ...field.Expr) gen.Columns { return p.programWeekDo.Columns(cols...) }

func (p *programWeek) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *programWeek) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 7)
	p.fieldMap["id"] = p.ID
	p.fieldMap["program_id"] = p.ProgramID
	p.fieldMap["sequence"] = p.Sequence
	p.fieldMap["name"] = p.Name
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt

}

func (p programWeek) clone(db *gorm.DB) programWeek {
	p.programWeekDo.ReplaceConnPool(db.Statement.ConnPool)
	p.Days.db = db.Session(&gorm.Session{Initialized: true})
	p.Days.db.Statement.ConnPool = db.Statement.ConnPool
	return p
}

func (p programWeek) replaceDB(db *gorm.DB) programWeek {
	p.programWeekDo.ReplaceDB(db)
	p.Days.db = db.Session(&gorm.Session{})
	return p
}

type programWeekHasManyDays struct {
	db *gorm.DB

	field.RelationField

	Exercises struct {
		field.RelationField
		Groups struct {
			field.RelationField
			Sets struct {
				field.RelationField
			}
		}
	}
}

func (a programWeekHasManyDays) Where(conds ...field.Expr) *programWeekHasManyDays {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a programWeekHasManyDays) WithContext(ctx context.Context) *programWeekHasManyDays {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a programWeekHasManyDays) Session(session *gorm.Session) *programWeekHasManyDays {
	a.db = a.db.Session(session)
	return &a
}

func (a programWeekHasManyDays) Model(m *generated.ProgramWeek) *programWeekHasManyDaysTx {
	return &programWeekHasManyDaysTx{a.db.Model(m).Association(a.Name())}
}

func (a programWeekHasManyDays) Unscoped() *programWeekHasManyDays {
	a.db = a.db.Unscoped()
	return &a
}

type programWeekHasManyDaysTx struct{ tx *gorm.Association }

func (a programWeekHasManyDaysTx) Find() (result []*generated.ProgramDay, err error) {
	return result, a.tx.Find(&result)
}

func (a programWeekHasManyDaysTx) Append(values ...*generated.ProgramDay) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a programWeekHasManyDaysTx) Replace(values ...*generated.ProgramDay) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a programWeekHasManyDaysTx) Delete(values ...*generated.ProgramDay) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a programWeekHasManyDaysTx) Clear() error {
	return a.tx.Clear()
}

func (a programWeekHasManyDaysTx) Count() int64 {
	return a.tx.Count()
}

func (a programWeekHasManyDaysTx) Unscoped() *programWeekHasManyDaysTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type programWeekDo struct{ gen.DO }

func (p programWeekDo) Debug() *programWeekDo {
	return p.withDO(p.DO.Debug())
}

func (p programWeekDo) WithContext(ctx context.Context) *programWeekDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p programWeekDo) ReadDB() *programWeekDo {
	return p.Clauses(dbresolver.Read)
}

func (p programWeekDo) WriteDB() *programWeekDo {
	return p.Clauses(dbresolver.Write)
}

func (p programWeekDo) Session(config *gorm.Session) *programWeekDo {
	return p.withDO(p.DO.Session(config))
}

func (p programWeekDo) Clauses(conds ...clause.Expression) *programWeekDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p programWeekDo) Returning(value interface{}, columns ...string) *programWeekDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p programWeekDo) Not(conds ...gen.Condition) *programWeekDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p programWeekDo) Or(conds ...gen.Condition) *programWeekDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p programWeekDo) Select(conds ...field.Expr) *programWeekDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p programWeekDo) Where(conds ...gen.Condition) *programWeekDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p programWeekDo) Order(conds ...field.Expr) *programWeekDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p programWeekDo) Distinct(cols ...field.Expr) *programWeekDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p programWeekDo) Omit(cols ...field.Expr) *programWeekDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p programWeekDo) Join(table schema.Tabler, on ...field.Expr) *programWeekDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p programWeekDo) LeftJoin(table schema.Tabler, on ...field.Expr) *programWeekDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p programWeekDo) RightJoin(table schema.Tabler, on ...field.Expr) *programWeekDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p programWeekDo) Group(cols ...field.Expr) *programWeekDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p programWeekDo) Having(conds ...gen.Condition) *programWeekDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p programWeekDo) Limit(limit int) *programWeekDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p programWeekDo) Offset(offset int) *programWeekDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p programWeekDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *programWeekDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p programWeekDo) Unscoped() *programWeekDo {
	return p.withDO(p.DO.Unscoped())
}

func (p programWeekDo) Create(values ...*generated.ProgramWeek) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p programWeekDo) CreateInBatches(values []*generated.ProgramWeek, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p programWeekDo) Save(values ...*generated.ProgramWeek) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p programWeekDo) First() (*generated.ProgramWeek, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*generated.ProgramWeek), nil
	}
}

func (p programWeekDo) Take() (*generated.ProgramWeek, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*generated.ProgramWeek), nil
	}
}

func (p programWeekDo) Last() (*generated.ProgramWeek, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*generated.ProgramWeek), nil
	}
}

func (p programWeekDo) Find() ([]*generated.ProgramWeek, error) {
	result, err := p.DO.Find()
	return result.([]*generated.ProgramWeek), err
}

func (p programWeekDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*generated.ProgramWeek, err error) {
	buf := make([]*generated.ProgramWeek, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p programWeekDo) FindInBatches(result *[]*generated.ProgramWeek, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p programWeekDo) Attrs(attrs ...field.AssignExpr) *programWeekDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p programWeekDo) Assign(attrs ...field.AssignExpr) *programWeekDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p programWeekDo) Joins(fields ...field.RelationField) *programWeekDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p programWeekDo) Preload(fields ...field.RelationField) *programWeekDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p programWeekDo) FirstOrInit() (*generated.ProgramWeek, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*generated.ProgramWeek), nil
	}
}

func (p programWeekDo) FirstOrCreate() (*generated.ProgramWeek, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*generated.ProgramWeek), nil
	}
}

func (p programWeekDo) FindByPage(offset int, limit int) (result []*generated.ProgramWeek, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p programWeekDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p programWeekDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p programWeekDo) Delete(models ...*generated.ProgramWeek) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *programWeekDo) withDO(do gen.Dao) *programWeekDo {
	p.DO = *do.(*gen.DO)
	return p
}
