// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/thompsonlogan/fitlytics/backend/internal/models/generated"
)

func newProgramSetGroup(db *gorm.DB, opts ...gen.DOOption) programSetGroup {
	_programSetGroup := programSetGroup{}

	_programSetGroup.programSetGroupDo.UseDB(db, opts...)
	_programSetGroup.programSetGroupDo.UseModel(&generated.ProgramSetGroup{})

	tableName := _programSetGroup.programSetGroupDo.TableName()
	_programSetGroup.ALL = field.NewAsterisk(tableName)
	_programSetGroup.ID = field.NewField(tableName, "id")
	_programSetGroup.ProgramExerciseID = field.NewField(tableName, "program_exercise_id")
	_programSetGroup.Sequence = field.NewInt32(tableName, "sequence")
	_programSetGroup.CreatedAt = field.NewTime(tableName, "created_at")
	_programSetGroup.UpdatedAt = field.NewTime(tableName, "updated_at")
	_programSetGroup.Sets = programSetGroupHasManySets{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Sets", "generated.ProgramSet"),
	}

	_programSetGroup.fillFieldMap()

	return _programSetGroup
}

type programSetGroup struct {
	programSetGroupDo programSetGroupDo

	ALL               field.Asterisk
	ID                field.Field
	ProgramExerciseID field.Field
	Sequence          field.Int32
	CreatedAt         field.Time
	UpdatedAt         field.Time
	Sets              programSetGroupHasManySets

	fieldMap map[string]field.Expr
}

func (p programSetGroup) Table(newTableName string) *programSetGroup {
	p.programSetGroupDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p programSetGroup) As(alias string) *programSetGroup {
	p.programSetGroupDo.DO = *(p.programSetGroupDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *programSetGroup) updateTableName(table string) *programSetGroup {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewField(table, "id")
	p.ProgramExerciseID = field.NewField(table, "program_exercise_id")
	p.Sequence = field.NewInt32(table, "sequence")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")

	p.fillFieldMap()

	return p
}

func (p *programSetGroup) WithContext(ctx context.Context) *programSetGroupDo {
	return p.programSetGroupDo.WithContext(ctx)
}

func (p programSetGroup) TableName() string { return p.programSetGroupDo.TableName() }

func (p programSetGroup) Alias() string { return p.programSetGroupDo.Alias() }

func (p programSetGroup) Columns(cols ...field.Expr) gen.Columns {
	return p.programSetGroupDo.Columns(cols...)
}

func (p *programSetGroup) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *programSetGroup) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 6)
	p.fieldMap["id"] = p.ID
	p.fieldMap["program_exercise_id"] = p.ProgramExerciseID
	p.fieldMap["sequence"] = p.Sequence
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt

}

func (p programSetGroup) clone(db *gorm.DB) programSetGroup {
	p.programSetGroupDo.ReplaceConnPool(db.Statement.ConnPool)
	p.Sets.db = db.Session(&gorm.Session{Initialized: true})
	p.Sets.db.Statement.ConnPool = db.Statement.ConnPool
	return p
}

func (p programSetGroup) replaceDB(db *gorm.DB) programSetGroup {
	p.programSetGroupDo.ReplaceDB(db)
	p.Sets.db = db.Session(&gorm.Session{})
	return p
}

type programSetGroupHasManySets struct {
	db *gorm.DB

	field.RelationField
}

func (a programSetGroupHasManySets) Where(conds ...field.Expr) *programSetGroupHasManySets {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a programSetGroupHasManySets) WithContext(ctx context.Context) *programSetGroupHasManySets {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a programSetGroupHasManySets) Session(session *gorm.Session) *programSetGroupHasManySets {
	a.db = a.db.Session(session)
	return &a
}

func (a programSetGroupHasManySets) Model(m *generated.ProgramSetGroup) *programSetGroupHasManySetsTx {
	return &programSetGroupHasManySetsTx{a.db.Model(m).Association(a.Name())}
}

func (a programSetGroupHasManySets) Unscoped() *programSetGroupHasManySets {
	a.db = a.db.Unscoped()
	return &a
}

type programSetGroupHasManySetsTx struct{ tx *gorm.Association }

func (a programSetGroupHasManySetsTx) Find() (result []*generated.ProgramSet, err error) {
	return result, a.tx.Find(&result)
}

func (a programSetGroupHasManySetsTx) Append(values ...*generated.ProgramSet) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a programSetGroupHasManySetsTx) Replace(values ...*generated.ProgramSet) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a programSetGroupHasManySetsTx) Delete(values ...*generated.ProgramSet) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a programSetGroupHasManySetsTx) Clear() error {
	return a.tx.Clear()
}

func (a programSetGroupHasManySetsTx) Count() int64 {
	return a.tx.Count()
}

func (a programSetGroupHasManySetsTx) Unscoped() *programSetGroupHasManySetsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type programSetGroupDo struct{ gen.DO }

func (p programSetGroupDo) Debug() *programSetGroupDo {
	return p.withDO(p.DO.Debug())
}

func (p programSetGroupDo) WithContext(ctx context.Context) *programSetGroupDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p programSetGroupDo) ReadDB() *programSetGroupDo {
	return p.Clauses(dbresolver.Read)
}

func (p programSetGroupDo) WriteDB() *programSetGroupDo {
	return p.Clauses(dbresolver.Write)
}

func (p programSetGroupDo) Session(config *gorm.Session) *programSetGroupDo {
	return p.withDO(p.DO.Session(config))
}

func (p programSetGroupDo) Clauses(conds ...clause.Expression) *programSetGroupDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p programSetGroupDo) Returning(value interface{}, columns ...string) *programSetGroupDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p programSetGroupDo) Not(conds ...gen.Condition) *programSetGroupDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p programSetGroupDo) Or(conds ...gen.Condition) *programSetGroupDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p programSetGroupDo) Select(conds ...field.Expr) *programSetGroupDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p programSetGroupDo) Where(conds ...gen.Condition) *programSetGroupDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p programSetGroupDo) Order(conds ...field.Expr) *programSetGroupDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p programSetGroupDo) Distinct(cols ...field.Expr) *programSetGroupDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p programSetGroupDo) Omit(cols ...field.Expr) *programSetGroupDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p programSetGroupDo) Join(table schema.Tabler, on ...field.Expr) *programSetGroupDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p programSetGroupDo) LeftJoin(table schema.Tabler, on ...field.Expr) *programSetGroupDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p programSetGroupDo) RightJoin(table schema.Tabler, on ...field.Expr) *programSetGroupDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p programSetGroupDo) Group(cols ...field.Expr) *programSetGroupDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p programSetGroupDo) Having(conds ...gen.Condition) *programSetGroupDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p programSetGroupDo) Limit(limit int) *programSetGroupDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p programSetGroupDo) Offset(offset int) *programSetGroupDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p programSetGroupDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *programSetGroupDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p programSetGroupDo) Unscoped() *programSetGroupDo {
	return p.withDO(p.DO.Unscoped())
}

func (p programSetGroupDo) Create(values ...*generated.ProgramSetGroup) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p programSetGroupDo) CreateInBatches(values []*generated.ProgramSetGroup, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p programSetGroupDo) Save(values ...*generated.ProgramSetGroup) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p programSetGroupDo) First() (*generated.ProgramSetGroup, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*generated.ProgramSetGroup), nil
	}
}

func (p programSetGroupDo) Take() (*generated.ProgramSetGroup, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*generated.ProgramSetGroup), nil
	}
}

func (p programSetGroupDo) Last() (*generated.ProgramSetGroup, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*generated.ProgramSetGroup), nil
	}
}

func (p programSetGroupDo) Find() ([]*generated.ProgramSetGroup, error) {
	result, err := p.DO.Find()
	return result.([]*generated.ProgramSetGroup), err
}

func (p programSetGroupDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*generated.ProgramSetGroup, err error) {
	buf := make([]*generated.ProgramSetGroup, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p programSetGroupDo) FindInBatches(result *[]*generated.ProgramSetGroup, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p programSetGroupDo) Attrs(attrs ...field.AssignExpr) *programSetGroupDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p programSetGroupDo) Assign(attrs ...field.AssignExpr) *programSetGroupDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p programSetGroupDo) Joins(fields ...field.RelationField) *programSetGroupDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p programSetGroupDo) Preload(fields ...field.RelationField) *programSetGroupDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p programSetGroupDo) FirstOrInit() (*generated.ProgramSetGroup, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*generated.ProgramSetGroup), nil
	}
}

func (p programSetGroupDo) FirstOrCreate() (*generated.ProgramSetGroup, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*generated.ProgramSetGroup), nil
	}
}

func (p programSetGroupDo) FindByPage(offset int, limit int) (result []*generated.ProgramSetGroup, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p programSetGroupDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p programSetGroupDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p programSetGroupDo) Delete(models ...*generated.ProgramSetGroup) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *programSetGroupDo) withDO(do gen.Dao) *programSetGroupDo {
	p.DO = *do.(*gen.DO)
	return p
}
