// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/thompsonlogan/fitlytics/backend/internal/models/generated"
)

func newProgramDay(db *gorm.DB, opts ...gen.DOOption) programDay {
	_programDay := programDay{}

	_programDay.programDayDo.UseDB(db, opts...)
	_programDay.programDayDo.UseModel(&generated.ProgramDay{})

	tableName := _programDay.programDayDo.TableName()
	_programDay.ALL = field.NewAsterisk(tableName)
	_programDay.ID = field.NewField(tableName, "id")
	_programDay.WeekID = field.NewField(tableName, "week_id")
	_programDay.Sequence = field.NewInt32(tableName, "sequence")
	_programDay.Name = field.NewString(tableName, "name")
	_programDay.Tag = field.NewString(tableName, "tag")
	_programDay.IsRestDay = field.NewBool(tableName, "is_rest_day")
	_programDay.Notes = field.NewString(tableName, "notes")
	_programDay.CreatedAt = field.NewTime(tableName, "created_at")
	_programDay.UpdatedAt = field.NewTime(tableName, "updated_at")
	_programDay.Exercises = programDayHasManyExercises{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Exercises", "generated.ProgramExercise"),
		SetTargets: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Exercises.SetTargets", "generated.ProgramSetTarget"),
		},
	}

	_programDay.fillFieldMap()

	return _programDay
}

type programDay struct {
	programDayDo programDayDo

	ALL       field.Asterisk
	ID        field.Field
	WeekID    field.Field
	Sequence  field.Int32
	Name      field.String
	Tag       field.String
	IsRestDay field.Bool
	Notes     field.String
	CreatedAt field.Time
	UpdatedAt field.Time
	Exercises programDayHasManyExercises

	fieldMap map[string]field.Expr
}

func (p programDay) Table(newTableName string) *programDay {
	p.programDayDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p programDay) As(alias string) *programDay {
	p.programDayDo.DO = *(p.programDayDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *programDay) updateTableName(table string) *programDay {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewField(table, "id")
	p.WeekID = field.NewField(table, "week_id")
	p.Sequence = field.NewInt32(table, "sequence")
	p.Name = field.NewString(table, "name")
	p.Tag = field.NewString(table, "tag")
	p.IsRestDay = field.NewBool(table, "is_rest_day")
	p.Notes = field.NewString(table, "notes")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")

	p.fillFieldMap()

	return p
}

func (p *programDay) WithContext(ctx context.Context) *programDayDo {
	return p.programDayDo.WithContext(ctx)
}

func (p programDay) TableName() string { return p.programDayDo.TableName() }

func (p programDay) Alias() string { return p.programDayDo.Alias() }

func (p programDay) Columns(cols ...field.Expr) gen.Columns { return p.programDayDo.Columns(cols...) }

func (p *programDay) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *programDay) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 10)
	p.fieldMap["id"] = p.ID
	p.fieldMap["week_id"] = p.WeekID
	p.fieldMap["sequence"] = p.Sequence
	p.fieldMap["name"] = p.Name
	p.fieldMap["tag"] = p.Tag
	p.fieldMap["is_rest_day"] = p.IsRestDay
	p.fieldMap["notes"] = p.Notes
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt

}

func (p programDay) clone(db *gorm.DB) programDay {
	p.programDayDo.ReplaceConnPool(db.Statement.ConnPool)
	p.Exercises.db = db.Session(&gorm.Session{Initialized: true})
	p.Exercises.db.Statement.ConnPool = db.Statement.ConnPool
	return p
}

func (p programDay) replaceDB(db *gorm.DB) programDay {
	p.programDayDo.ReplaceDB(db)
	p.Exercises.db = db.Session(&gorm.Session{})
	return p
}

type programDayHasManyExercises struct {
	db *gorm.DB

	field.RelationField

	SetTargets struct {
		field.RelationField
	}
}

func (a programDayHasManyExercises) Where(conds ...field.Expr) *programDayHasManyExercises {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a programDayHasManyExercises) WithContext(ctx context.Context) *programDayHasManyExercises {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a programDayHasManyExercises) Session(session *gorm.Session) *programDayHasManyExercises {
	a.db = a.db.Session(session)
	return &a
}

func (a programDayHasManyExercises) Model(m *generated.ProgramDay) *programDayHasManyExercisesTx {
	return &programDayHasManyExercisesTx{a.db.Model(m).Association(a.Name())}
}

func (a programDayHasManyExercises) Unscoped() *programDayHasManyExercises {
	a.db = a.db.Unscoped()
	return &a
}

type programDayHasManyExercisesTx struct{ tx *gorm.Association }

func (a programDayHasManyExercisesTx) Find() (result []*generated.ProgramExercise, err error) {
	return result, a.tx.Find(&result)
}

func (a programDayHasManyExercisesTx) Append(values ...*generated.ProgramExercise) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a programDayHasManyExercisesTx) Replace(values ...*generated.ProgramExercise) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a programDayHasManyExercisesTx) Delete(values ...*generated.ProgramExercise) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a programDayHasManyExercisesTx) Clear() error {
	return a.tx.Clear()
}

func (a programDayHasManyExercisesTx) Count() int64 {
	return a.tx.Count()
}

func (a programDayHasManyExercisesTx) Unscoped() *programDayHasManyExercisesTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type programDayDo struct{ gen.DO }

func (p programDayDo) Debug() *programDayDo {
	return p.withDO(p.DO.Debug())
}

func (p programDayDo) WithContext(ctx context.Context) *programDayDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p programDayDo) ReadDB() *programDayDo {
	return p.Clauses(dbresolver.Read)
}

func (p programDayDo) WriteDB() *programDayDo {
	return p.Clauses(dbresolver.Write)
}

func (p programDayDo) Session(config *gorm.Session) *programDayDo {
	return p.withDO(p.DO.Session(config))
}

func (p programDayDo) Clauses(conds ...clause.Expression) *programDayDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p programDayDo) Returning(value interface{}, columns ...string) *programDayDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p programDayDo) Not(conds ...gen.Condition) *programDayDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p programDayDo) Or(conds ...gen.Condition) *programDayDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p programDayDo) Select(conds ...field.Expr) *programDayDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p programDayDo) Where(conds ...gen.Condition) *programDayDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p programDayDo) Order(conds ...field.Expr) *programDayDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p programDayDo) Distinct(cols ...field.Expr) *programDayDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p programDayDo) Omit(cols ...field.Expr) *programDayDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p programDayDo) Join(table schema.Tabler, on ...field.Expr) *programDayDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p programDayDo) LeftJoin(table schema.Tabler, on ...field.Expr) *programDayDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p programDayDo) RightJoin(table schema.Tabler, on ...field.Expr) *programDayDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p programDayDo) Group(cols ...field.Expr) *programDayDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p programDayDo) Having(conds ...gen.Condition) *programDayDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p programDayDo) Limit(limit int) *programDayDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p programDayDo) Offset(offset int) *programDayDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p programDayDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *programDayDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p programDayDo) Unscoped() *programDayDo {
	return p.withDO(p.DO.Unscoped())
}

func (p programDayDo) Create(values ...*generated.ProgramDay) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p programDayDo) CreateInBatches(values []*generated.ProgramDay, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p programDayDo) Save(values ...*generated.ProgramDay) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p programDayDo) First() (*generated.ProgramDay, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*generated.ProgramDay), nil
	}
}

func (p programDayDo) Take() (*generated.ProgramDay, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*generated.ProgramDay), nil
	}
}

func (p programDayDo) Last() (*generated.ProgramDay, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*generated.ProgramDay), nil
	}
}

func (p programDayDo) Find() ([]*generated.ProgramDay, error) {
	result, err := p.DO.Find()
	return result.([]*generated.ProgramDay), err
}

func (p programDayDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*generated.ProgramDay, err error) {
	buf := make([]*generated.ProgramDay, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p programDayDo) FindInBatches(result *[]*generated.ProgramDay, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p programDayDo) Attrs(attrs ...field.AssignExpr) *programDayDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p programDayDo) Assign(attrs ...field.AssignExpr) *programDayDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p programDayDo) Joins(fields ...field.RelationField) *programDayDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p programDayDo) Preload(fields ...field.RelationField) *programDayDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p programDayDo) FirstOrInit() (*generated.ProgramDay, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*generated.ProgramDay), nil
	}
}

func (p programDayDo) FirstOrCreate() (*generated.ProgramDay, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*generated.ProgramDay), nil
	}
}

func (p programDayDo) FindByPage(offset int, limit int) (result []*generated.ProgramDay, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p programDayDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p programDayDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p programDayDo) Delete(models ...*generated.ProgramDay) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *programDayDo) withDO(do gen.Dao) *programDayDo {
	p.DO = *do.(*gen.DO)
	return p
}
