// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/thompsonlogan/fitlytics/backend/internal/models/generated"
)

func newSession(db *gorm.DB, opts ...gen.DOOption) session {
	_session := session{}

	_session.sessionDo.UseDB(db, opts...)
	_session.sessionDo.UseModel(&generated.Session{})

	tableName := _session.sessionDo.TableName()
	_session.ALL = field.NewAsterisk(tableName)
	_session.ID = field.NewField(tableName, "id")
	_session.UserID = field.NewField(tableName, "user_id")
	_session.ProgramDayID = field.NewField(tableName, "program_day_id")
	_session.ProgramNameSnapshot = field.NewString(tableName, "program_name_snapshot")
	_session.DayNameSnapshot = field.NewString(tableName, "day_name_snapshot")
	_session.State = field.NewString(tableName, "state")
	_session.StartedAt = field.NewTime(tableName, "started_at")
	_session.CompletedAt = field.NewTime(tableName, "completed_at")
	_session.Notes = field.NewString(tableName, "notes")
	_session.CreatedAt = field.NewTime(tableName, "created_at")
	_session.UpdatedAt = field.NewTime(tableName, "updated_at")
	_session.DeletedAt = field.NewField(tableName, "deleted_at")
	_session.Exercises = sessionHasManyExercises{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Exercises", "generated.SessionExercise"),
		SetLogs: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Exercises.SetLogs", "generated.SetLog"),
		},
	}

	_session.fillFieldMap()

	return _session
}

type session struct {
	sessionDo sessionDo

	ALL                 field.Asterisk
	ID                  field.Field
	UserID              field.Field
	ProgramDayID        field.Field
	ProgramNameSnapshot field.String
	DayNameSnapshot     field.String
	State               field.String
	StartedAt           field.Time
	CompletedAt         field.Time
	Notes               field.String
	CreatedAt           field.Time
	UpdatedAt           field.Time
	DeletedAt           field.Field
	Exercises           sessionHasManyExercises

	fieldMap map[string]field.Expr
}

func (s session) Table(newTableName string) *session {
	s.sessionDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s session) As(alias string) *session {
	s.sessionDo.DO = *(s.sessionDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *session) updateTableName(table string) *session {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewField(table, "id")
	s.UserID = field.NewField(table, "user_id")
	s.ProgramDayID = field.NewField(table, "program_day_id")
	s.ProgramNameSnapshot = field.NewString(table, "program_name_snapshot")
	s.DayNameSnapshot = field.NewString(table, "day_name_snapshot")
	s.State = field.NewString(table, "state")
	s.StartedAt = field.NewTime(table, "started_at")
	s.CompletedAt = field.NewTime(table, "completed_at")
	s.Notes = field.NewString(table, "notes")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.DeletedAt = field.NewField(table, "deleted_at")

	s.fillFieldMap()

	return s
}

func (s *session) WithContext(ctx context.Context) *sessionDo { return s.sessionDo.WithContext(ctx) }

func (s session) TableName() string { return s.sessionDo.TableName() }

func (s session) Alias() string { return s.sessionDo.Alias() }

func (s session) Columns(cols ...field.Expr) gen.Columns { return s.sessionDo.Columns(cols...) }

func (s *session) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *session) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 13)
	s.fieldMap["id"] = s.ID
	s.fieldMap["user_id"] = s.UserID
	s.fieldMap["program_day_id"] = s.ProgramDayID
	s.fieldMap["program_name_snapshot"] = s.ProgramNameSnapshot
	s.fieldMap["day_name_snapshot"] = s.DayNameSnapshot
	s.fieldMap["state"] = s.State
	s.fieldMap["started_at"] = s.StartedAt
	s.fieldMap["completed_at"] = s.CompletedAt
	s.fieldMap["notes"] = s.Notes
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["deleted_at"] = s.DeletedAt

}

func (s session) clone(db *gorm.DB) session {
	s.sessionDo.ReplaceConnPool(db.Statement.ConnPool)
	s.Exercises.db = db.Session(&gorm.Session{Initialized: true})
	s.Exercises.db.Statement.ConnPool = db.Statement.ConnPool
	return s
}

func (s session) replaceDB(db *gorm.DB) session {
	s.sessionDo.ReplaceDB(db)
	s.Exercises.db = db.Session(&gorm.Session{})
	return s
}

type sessionHasManyExercises struct {
	db *gorm.DB

	field.RelationField

	SetLogs struct {
		field.RelationField
	}
}

func (a sessionHasManyExercises) Where(conds ...field.Expr) *sessionHasManyExercises {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a sessionHasManyExercises) WithContext(ctx context.Context) *sessionHasManyExercises {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a sessionHasManyExercises) Session(session *gorm.Session) *sessionHasManyExercises {
	a.db = a.db.Session(session)
	return &a
}

func (a sessionHasManyExercises) Model(m *generated.Session) *sessionHasManyExercisesTx {
	return &sessionHasManyExercisesTx{a.db.Model(m).Association(a.Name())}
}

func (a sessionHasManyExercises) Unscoped() *sessionHasManyExercises {
	a.db = a.db.Unscoped()
	return &a
}

type sessionHasManyExercisesTx struct{ tx *gorm.Association }

func (a sessionHasManyExercisesTx) Find() (result []*generated.SessionExercise, err error) {
	return result, a.tx.Find(&result)
}

func (a sessionHasManyExercisesTx) Append(values ...*generated.SessionExercise) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a sessionHasManyExercisesTx) Replace(values ...*generated.SessionExercise) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a sessionHasManyExercisesTx) Delete(values ...*generated.SessionExercise) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a sessionHasManyExercisesTx) Clear() error {
	return a.tx.Clear()
}

func (a sessionHasManyExercisesTx) Count() int64 {
	return a.tx.Count()
}

func (a sessionHasManyExercisesTx) Unscoped() *sessionHasManyExercisesTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type sessionDo struct{ gen.DO }

func (s sessionDo) Debug() *sessionDo {
	return s.withDO(s.DO.Debug())
}

func (s sessionDo) WithContext(ctx context.Context) *sessionDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sessionDo) ReadDB() *sessionDo {
	return s.Clauses(dbresolver.Read)
}

func (s sessionDo) WriteDB() *sessionDo {
	return s.Clauses(dbresolver.Write)
}

func (s sessionDo) Session(config *gorm.Session) *sessionDo {
	return s.withDO(s.DO.Session(config))
}

func (s sessionDo) Clauses(conds ...clause.Expression) *sessionDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sessionDo) Returning(value interface{}, columns ...string) *sessionDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sessionDo) Not(conds ...gen.Condition) *sessionDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sessionDo) Or(conds ...gen.Condition) *sessionDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sessionDo) Select(conds ...field.Expr) *sessionDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sessionDo) Where(conds ...gen.Condition) *sessionDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sessionDo) Order(conds ...field.Expr) *sessionDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sessionDo) Distinct(cols ...field.Expr) *sessionDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sessionDo) Omit(cols ...field.Expr) *sessionDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sessionDo) Join(table schema.Tabler, on ...field.Expr) *sessionDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sessionDo) LeftJoin(table schema.Tabler, on ...field.Expr) *sessionDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sessionDo) RightJoin(table schema.Tabler, on ...field.Expr) *sessionDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sessionDo) Group(cols ...field.Expr) *sessionDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sessionDo) Having(conds ...gen.Condition) *sessionDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sessionDo) Limit(limit int) *sessionDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sessionDo) Offset(offset int) *sessionDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sessionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *sessionDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sessionDo) Unscoped() *sessionDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sessionDo) Create(values ...*generated.Session) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sessionDo) CreateInBatches(values []*generated.Session, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sessionDo) Save(values ...*generated.Session) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sessionDo) First() (*generated.Session, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*generated.Session), nil
	}
}

func (s sessionDo) Take() (*generated.Session, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*generated.Session), nil
	}
}

func (s sessionDo) Last() (*generated.Session, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*generated.Session), nil
	}
}

func (s sessionDo) Find() ([]*generated.Session, error) {
	result, err := s.DO.Find()
	return result.([]*generated.Session), err
}

func (s sessionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*generated.Session, err error) {
	buf := make([]*generated.Session, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sessionDo) FindInBatches(result *[]*generated.Session, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sessionDo) Attrs(attrs ...field.AssignExpr) *sessionDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sessionDo) Assign(attrs ...field.AssignExpr) *sessionDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sessionDo) Joins(fields ...field.RelationField) *sessionDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sessionDo) Preload(fields ...field.RelationField) *sessionDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sessionDo) FirstOrInit() (*generated.Session, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*generated.Session), nil
	}
}

func (s sessionDo) FirstOrCreate() (*generated.Session, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*generated.Session), nil
	}
}

func (s sessionDo) FindByPage(offset int, limit int) (result []*generated.Session, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sessionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sessionDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sessionDo) Delete(models ...*generated.Session) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sessionDo) withDO(do gen.Dao) *sessionDo {
	s.DO = *do.(*gen.DO)
	return s
}
