// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/thompsonlogan/fitlytics/backend/internal/models/generated"
)

func newSessionExercise(db *gorm.DB, opts ...gen.DOOption) sessionExercise {
	_sessionExercise := sessionExercise{}

	_sessionExercise.sessionExerciseDo.UseDB(db, opts...)
	_sessionExercise.sessionExerciseDo.UseModel(&generated.SessionExercise{})

	tableName := _sessionExercise.sessionExerciseDo.TableName()
	_sessionExercise.ALL = field.NewAsterisk(tableName)
	_sessionExercise.ID = field.NewField(tableName, "id")
	_sessionExercise.SessionID = field.NewField(tableName, "session_id")
	_sessionExercise.Sequence = field.NewInt32(tableName, "sequence")
	_sessionExercise.ExerciseID = field.NewField(tableName, "exercise_id")
	_sessionExercise.ExerciseNameSnap = field.NewString(tableName, "exercise_name_snap")
	_sessionExercise.SubSnap = field.NewString(tableName, "sub_snap")
	_sessionExercise.RestSecondsSnap = field.NewInt32(tableName, "rest_seconds_snap")
	_sessionExercise.Notes = field.NewString(tableName, "notes")
	_sessionExercise.Extras = field.NewField(tableName, "extras")
	_sessionExercise.CreatedAt = field.NewTime(tableName, "created_at")
	_sessionExercise.UpdatedAt = field.NewTime(tableName, "updated_at")
	_sessionExercise.SetLogs = sessionExerciseHasManySetLogs{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("SetLogs", "generated.SetLog"),
	}

	_sessionExercise.fillFieldMap()

	return _sessionExercise
}

type sessionExercise struct {
	sessionExerciseDo sessionExerciseDo

	ALL              field.Asterisk
	ID               field.Field
	SessionID        field.Field
	Sequence         field.Int32
	ExerciseID       field.Field
	ExerciseNameSnap field.String
	SubSnap          field.String
	RestSecondsSnap  field.Int32
	Notes            field.String
	Extras           field.Field
	CreatedAt        field.Time
	UpdatedAt        field.Time
	SetLogs          sessionExerciseHasManySetLogs

	fieldMap map[string]field.Expr
}

func (s sessionExercise) Table(newTableName string) *sessionExercise {
	s.sessionExerciseDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sessionExercise) As(alias string) *sessionExercise {
	s.sessionExerciseDo.DO = *(s.sessionExerciseDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sessionExercise) updateTableName(table string) *sessionExercise {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewField(table, "id")
	s.SessionID = field.NewField(table, "session_id")
	s.Sequence = field.NewInt32(table, "sequence")
	s.ExerciseID = field.NewField(table, "exercise_id")
	s.ExerciseNameSnap = field.NewString(table, "exercise_name_snap")
	s.SubSnap = field.NewString(table, "sub_snap")
	s.RestSecondsSnap = field.NewInt32(table, "rest_seconds_snap")
	s.Notes = field.NewString(table, "notes")
	s.Extras = field.NewField(table, "extras")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")

	s.fillFieldMap()

	return s
}

func (s *sessionExercise) WithContext(ctx context.Context) *sessionExerciseDo {
	return s.sessionExerciseDo.WithContext(ctx)
}

func (s sessionExercise) TableName() string { return s.sessionExerciseDo.TableName() }

func (s sessionExercise) Alias() string { return s.sessionExerciseDo.Alias() }

func (s sessionExercise) Columns(cols ...field.Expr) gen.Columns {
	return s.sessionExerciseDo.Columns(cols...)
}

func (s *sessionExercise) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sessionExercise) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 12)
	s.fieldMap["id"] = s.ID
	s.fieldMap["session_id"] = s.SessionID
	s.fieldMap["sequence"] = s.Sequence
	s.fieldMap["exercise_id"] = s.ExerciseID
	s.fieldMap["exercise_name_snap"] = s.ExerciseNameSnap
	s.fieldMap["sub_snap"] = s.SubSnap
	s.fieldMap["rest_seconds_snap"] = s.RestSecondsSnap
	s.fieldMap["notes"] = s.Notes
	s.fieldMap["extras"] = s.Extras
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt

}

func (s sessionExercise) clone(db *gorm.DB) sessionExercise {
	s.sessionExerciseDo.ReplaceConnPool(db.Statement.ConnPool)
	s.SetLogs.db = db.Session(&gorm.Session{Initialized: true})
	s.SetLogs.db.Statement.ConnPool = db.Statement.ConnPool
	return s
}

func (s sessionExercise) replaceDB(db *gorm.DB) sessionExercise {
	s.sessionExerciseDo.ReplaceDB(db)
	s.SetLogs.db = db.Session(&gorm.Session{})
	return s
}

type sessionExerciseHasManySetLogs struct {
	db *gorm.DB

	field.RelationField
}

func (a sessionExerciseHasManySetLogs) Where(conds ...field.Expr) *sessionExerciseHasManySetLogs {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a sessionExerciseHasManySetLogs) WithContext(ctx context.Context) *sessionExerciseHasManySetLogs {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a sessionExerciseHasManySetLogs) Session(session *gorm.Session) *sessionExerciseHasManySetLogs {
	a.db = a.db.Session(session)
	return &a
}

func (a sessionExerciseHasManySetLogs) Model(m *generated.SessionExercise) *sessionExerciseHasManySetLogsTx {
	return &sessionExerciseHasManySetLogsTx{a.db.Model(m).Association(a.Name())}
}

func (a sessionExerciseHasManySetLogs) Unscoped() *sessionExerciseHasManySetLogs {
	a.db = a.db.Unscoped()
	return &a
}

type sessionExerciseHasManySetLogsTx struct{ tx *gorm.Association }

func (a sessionExerciseHasManySetLogsTx) Find() (result []*generated.SetLog, err error) {
	return result, a.tx.Find(&result)
}

func (a sessionExerciseHasManySetLogsTx) Append(values ...*generated.SetLog) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a sessionExerciseHasManySetLogsTx) Replace(values ...*generated.SetLog) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a sessionExerciseHasManySetLogsTx) Delete(values ...*generated.SetLog) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a sessionExerciseHasManySetLogsTx) Clear() error {
	return a.tx.Clear()
}

func (a sessionExerciseHasManySetLogsTx) Count() int64 {
	return a.tx.Count()
}

func (a sessionExerciseHasManySetLogsTx) Unscoped() *sessionExerciseHasManySetLogsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type sessionExerciseDo struct{ gen.DO }

func (s sessionExerciseDo) Debug() *sessionExerciseDo {
	return s.withDO(s.DO.Debug())
}

func (s sessionExerciseDo) WithContext(ctx context.Context) *sessionExerciseDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sessionExerciseDo) ReadDB() *sessionExerciseDo {
	return s.Clauses(dbresolver.Read)
}

func (s sessionExerciseDo) WriteDB() *sessionExerciseDo {
	return s.Clauses(dbresolver.Write)
}

func (s sessionExerciseDo) Session(config *gorm.Session) *sessionExerciseDo {
	return s.withDO(s.DO.Session(config))
}

func (s sessionExerciseDo) Clauses(conds ...clause.Expression) *sessionExerciseDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sessionExerciseDo) Returning(value interface{}, columns ...string) *sessionExerciseDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sessionExerciseDo) Not(conds ...gen.Condition) *sessionExerciseDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sessionExerciseDo) Or(conds ...gen.Condition) *sessionExerciseDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sessionExerciseDo) Select(conds ...field.Expr) *sessionExerciseDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sessionExerciseDo) Where(conds ...gen.Condition) *sessionExerciseDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sessionExerciseDo) Order(conds ...field.Expr) *sessionExerciseDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sessionExerciseDo) Distinct(cols ...field.Expr) *sessionExerciseDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sessionExerciseDo) Omit(cols ...field.Expr) *sessionExerciseDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sessionExerciseDo) Join(table schema.Tabler, on ...field.Expr) *sessionExerciseDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sessionExerciseDo) LeftJoin(table schema.Tabler, on ...field.Expr) *sessionExerciseDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sessionExerciseDo) RightJoin(table schema.Tabler, on ...field.Expr) *sessionExerciseDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sessionExerciseDo) Group(cols ...field.Expr) *sessionExerciseDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sessionExerciseDo) Having(conds ...gen.Condition) *sessionExerciseDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sessionExerciseDo) Limit(limit int) *sessionExerciseDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sessionExerciseDo) Offset(offset int) *sessionExerciseDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sessionExerciseDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *sessionExerciseDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sessionExerciseDo) Unscoped() *sessionExerciseDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sessionExerciseDo) Create(values ...*generated.SessionExercise) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sessionExerciseDo) CreateInBatches(values []*generated.SessionExercise, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sessionExerciseDo) Save(values ...*generated.SessionExercise) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sessionExerciseDo) First() (*generated.SessionExercise, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*generated.SessionExercise), nil
	}
}

func (s sessionExerciseDo) Take() (*generated.SessionExercise, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*generated.SessionExercise), nil
	}
}

func (s sessionExerciseDo) Last() (*generated.SessionExercise, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*generated.SessionExercise), nil
	}
}

func (s sessionExerciseDo) Find() ([]*generated.SessionExercise, error) {
	result, err := s.DO.Find()
	return result.([]*generated.SessionExercise), err
}

func (s sessionExerciseDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*generated.SessionExercise, err error) {
	buf := make([]*generated.SessionExercise, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sessionExerciseDo) FindInBatches(result *[]*generated.SessionExercise, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sessionExerciseDo) Attrs(attrs ...field.AssignExpr) *sessionExerciseDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sessionExerciseDo) Assign(attrs ...field.AssignExpr) *sessionExerciseDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sessionExerciseDo) Joins(fields ...field.RelationField) *sessionExerciseDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sessionExerciseDo) Preload(fields ...field.RelationField) *sessionExerciseDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sessionExerciseDo) FirstOrInit() (*generated.SessionExercise, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*generated.SessionExercise), nil
	}
}

func (s sessionExerciseDo) FirstOrCreate() (*generated.SessionExercise, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*generated.SessionExercise), nil
	}
}

func (s sessionExerciseDo) FindByPage(offset int, limit int) (result []*generated.SessionExercise, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sessionExerciseDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sessionExerciseDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sessionExerciseDo) Delete(models ...*generated.SessionExercise) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sessionExerciseDo) withDO(do gen.Dao) *sessionExerciseDo {
	s.DO = *do.(*gen.DO)
	return s
}
