// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/thompsonlogan/fitlytics/backend/internal/models/generated"
)

func newSetLog(db *gorm.DB, opts ...gen.DOOption) setLog {
	_setLog := setLog{}

	_setLog.setLogDo.UseDB(db, opts...)
	_setLog.setLogDo.UseModel(&generated.SetLog{})

	tableName := _setLog.setLogDo.TableName()
	_setLog.ALL = field.NewAsterisk(tableName)
	_setLog.ID = field.NewField(tableName, "id")
	_setLog.SessionExerciseID = field.NewField(tableName, "session_exercise_id")
	_setLog.Sequence = field.NewInt32(tableName, "sequence")
	_setLog.BlockSequence = field.NewInt32(tableName, "block_sequence")
	_setLog.SetType = field.NewString(tableName, "set_type")
	_setLog.RepsTargetMin = field.NewInt32(tableName, "reps_target_min")
	_setLog.RepsTargetMax = field.NewInt32(tableName, "reps_target_max")
	_setLog.DurationTargetSec = field.NewInt32(tableName, "duration_target_sec")
	_setLog.DistanceTargetM = field.NewFloat64(tableName, "distance_target_m")
	_setLog.PrescribedLoadKg = field.NewFloat64(tableName, "prescribed_load_kg")
	_setLog.PrescribedLoadModifier = field.NewString(tableName, "prescribed_load_modifier")
	_setLog.PrescribedRpe = field.NewFloat64(tableName, "prescribed_rpe")
	_setLog.IntensityText = field.NewString(tableName, "intensity_text")
	_setLog.RepsActual = field.NewInt32(tableName, "reps_actual")
	_setLog.DurationActualSec = field.NewInt32(tableName, "duration_actual_sec")
	_setLog.DistanceActualM = field.NewFloat64(tableName, "distance_actual_m")
	_setLog.ActualLoadKg = field.NewFloat64(tableName, "actual_load_kg")
	_setLog.ActualLoadModifier = field.NewString(tableName, "actual_load_modifier")
	_setLog.ActualRpe = field.NewFloat64(tableName, "actual_rpe")
	_setLog.StartedAt = field.NewTime(tableName, "started_at")
	_setLog.CompletedAt = field.NewTime(tableName, "completed_at")
	_setLog.State = field.NewString(tableName, "state")
	_setLog.Notes = field.NewString(tableName, "notes")
	_setLog.CreatedAt = field.NewTime(tableName, "created_at")
	_setLog.UpdatedAt = field.NewTime(tableName, "updated_at")
	_setLog.DeletedAt = field.NewField(tableName, "deleted_at")

	_setLog.fillFieldMap()

	return _setLog
}

type setLog struct {
	setLogDo setLogDo

	ALL                    field.Asterisk
	ID                     field.Field
	SessionExerciseID      field.Field
	Sequence               field.Int32
	BlockSequence          field.Int32
	SetType                field.String
	RepsTargetMin          field.Int32
	RepsTargetMax          field.Int32
	DurationTargetSec      field.Int32
	DistanceTargetM        field.Float64
	PrescribedLoadKg       field.Float64
	PrescribedLoadModifier field.String
	PrescribedRpe          field.Float64
	IntensityText          field.String
	RepsActual             field.Int32
	DurationActualSec      field.Int32
	DistanceActualM        field.Float64
	ActualLoadKg           field.Float64
	ActualLoadModifier     field.String
	ActualRpe              field.Float64
	StartedAt              field.Time
	CompletedAt            field.Time
	State                  field.String
	Notes                  field.String
	CreatedAt              field.Time
	UpdatedAt              field.Time
	DeletedAt              field.Field

	fieldMap map[string]field.Expr
}

func (s setLog) Table(newTableName string) *setLog {
	s.setLogDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s setLog) As(alias string) *setLog {
	s.setLogDo.DO = *(s.setLogDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *setLog) updateTableName(table string) *setLog {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewField(table, "id")
	s.SessionExerciseID = field.NewField(table, "session_exercise_id")
	s.Sequence = field.NewInt32(table, "sequence")
	s.BlockSequence = field.NewInt32(table, "block_sequence")
	s.SetType = field.NewString(table, "set_type")
	s.RepsTargetMin = field.NewInt32(table, "reps_target_min")
	s.RepsTargetMax = field.NewInt32(table, "reps_target_max")
	s.DurationTargetSec = field.NewInt32(table, "duration_target_sec")
	s.DistanceTargetM = field.NewFloat64(table, "distance_target_m")
	s.PrescribedLoadKg = field.NewFloat64(table, "prescribed_load_kg")
	s.PrescribedLoadModifier = field.NewString(table, "prescribed_load_modifier")
	s.PrescribedRpe = field.NewFloat64(table, "prescribed_rpe")
	s.IntensityText = field.NewString(table, "intensity_text")
	s.RepsActual = field.NewInt32(table, "reps_actual")
	s.DurationActualSec = field.NewInt32(table, "duration_actual_sec")
	s.DistanceActualM = field.NewFloat64(table, "distance_actual_m")
	s.ActualLoadKg = field.NewFloat64(table, "actual_load_kg")
	s.ActualLoadModifier = field.NewString(table, "actual_load_modifier")
	s.ActualRpe = field.NewFloat64(table, "actual_rpe")
	s.StartedAt = field.NewTime(table, "started_at")
	s.CompletedAt = field.NewTime(table, "completed_at")
	s.State = field.NewString(table, "state")
	s.Notes = field.NewString(table, "notes")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.DeletedAt = field.NewField(table, "deleted_at")

	s.fillFieldMap()

	return s
}

func (s *setLog) WithContext(ctx context.Context) *setLogDo { return s.setLogDo.WithContext(ctx) }

func (s setLog) TableName() string { return s.setLogDo.TableName() }

func (s setLog) Alias() string { return s.setLogDo.Alias() }

func (s setLog) Columns(cols ...field.Expr) gen.Columns { return s.setLogDo.Columns(cols...) }

func (s *setLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *setLog) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 26)
	s.fieldMap["id"] = s.ID
	s.fieldMap["session_exercise_id"] = s.SessionExerciseID
	s.fieldMap["sequence"] = s.Sequence
	s.fieldMap["block_sequence"] = s.BlockSequence
	s.fieldMap["set_type"] = s.SetType
	s.fieldMap["reps_target_min"] = s.RepsTargetMin
	s.fieldMap["reps_target_max"] = s.RepsTargetMax
	s.fieldMap["duration_target_sec"] = s.DurationTargetSec
	s.fieldMap["distance_target_m"] = s.DistanceTargetM
	s.fieldMap["prescribed_load_kg"] = s.PrescribedLoadKg
	s.fieldMap["prescribed_load_modifier"] = s.PrescribedLoadModifier
	s.fieldMap["prescribed_rpe"] = s.PrescribedRpe
	s.fieldMap["intensity_text"] = s.IntensityText
	s.fieldMap["reps_actual"] = s.RepsActual
	s.fieldMap["duration_actual_sec"] = s.DurationActualSec
	s.fieldMap["distance_actual_m"] = s.DistanceActualM
	s.fieldMap["actual_load_kg"] = s.ActualLoadKg
	s.fieldMap["actual_load_modifier"] = s.ActualLoadModifier
	s.fieldMap["actual_rpe"] = s.ActualRpe
	s.fieldMap["started_at"] = s.StartedAt
	s.fieldMap["completed_at"] = s.CompletedAt
	s.fieldMap["state"] = s.State
	s.fieldMap["notes"] = s.Notes
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["deleted_at"] = s.DeletedAt
}

func (s setLog) clone(db *gorm.DB) setLog {
	s.setLogDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s setLog) replaceDB(db *gorm.DB) setLog {
	s.setLogDo.ReplaceDB(db)
	return s
}

type setLogDo struct{ gen.DO }

func (s setLogDo) Debug() *setLogDo {
	return s.withDO(s.DO.Debug())
}

func (s setLogDo) WithContext(ctx context.Context) *setLogDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s setLogDo) ReadDB() *setLogDo {
	return s.Clauses(dbresolver.Read)
}

func (s setLogDo) WriteDB() *setLogDo {
	return s.Clauses(dbresolver.Write)
}

func (s setLogDo) Session(config *gorm.Session) *setLogDo {
	return s.withDO(s.DO.Session(config))
}

func (s setLogDo) Clauses(conds ...clause.Expression) *setLogDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s setLogDo) Returning(value interface{}, columns ...string) *setLogDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s setLogDo) Not(conds ...gen.Condition) *setLogDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s setLogDo) Or(conds ...gen.Condition) *setLogDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s setLogDo) Select(conds ...field.Expr) *setLogDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s setLogDo) Where(conds ...gen.Condition) *setLogDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s setLogDo) Order(conds ...field.Expr) *setLogDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s setLogDo) Distinct(cols ...field.Expr) *setLogDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s setLogDo) Omit(cols ...field.Expr) *setLogDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s setLogDo) Join(table schema.Tabler, on ...field.Expr) *setLogDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s setLogDo) LeftJoin(table schema.Tabler, on ...field.Expr) *setLogDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s setLogDo) RightJoin(table schema.Tabler, on ...field.Expr) *setLogDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s setLogDo) Group(cols ...field.Expr) *setLogDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s setLogDo) Having(conds ...gen.Condition) *setLogDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s setLogDo) Limit(limit int) *setLogDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s setLogDo) Offset(offset int) *setLogDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s setLogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *setLogDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s setLogDo) Unscoped() *setLogDo {
	return s.withDO(s.DO.Unscoped())
}

func (s setLogDo) Create(values ...*generated.SetLog) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s setLogDo) CreateInBatches(values []*generated.SetLog, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s setLogDo) Save(values ...*generated.SetLog) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s setLogDo) First() (*generated.SetLog, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*generated.SetLog), nil
	}
}

func (s setLogDo) Take() (*generated.SetLog, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*generated.SetLog), nil
	}
}

func (s setLogDo) Last() (*generated.SetLog, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*generated.SetLog), nil
	}
}

func (s setLogDo) Find() ([]*generated.SetLog, error) {
	result, err := s.DO.Find()
	return result.([]*generated.SetLog), err
}

func (s setLogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*generated.SetLog, err error) {
	buf := make([]*generated.SetLog, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s setLogDo) FindInBatches(result *[]*generated.SetLog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s setLogDo) Attrs(attrs ...field.AssignExpr) *setLogDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s setLogDo) Assign(attrs ...field.AssignExpr) *setLogDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s setLogDo) Joins(fields ...field.RelationField) *setLogDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s setLogDo) Preload(fields ...field.RelationField) *setLogDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s setLogDo) FirstOrInit() (*generated.SetLog, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*generated.SetLog), nil
	}
}

func (s setLogDo) FirstOrCreate() (*generated.SetLog, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*generated.SetLog), nil
	}
}

func (s setLogDo) FindByPage(offset int, limit int) (result []*generated.SetLog, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s setLogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s setLogDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s setLogDo) Delete(models ...*generated.SetLog) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *setLogDo) withDO(do gen.Dao) *setLogDo {
	s.DO = *do.(*gen.DO)
	return s
}
