// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/thompsonlogan/fitlytics/backend/internal/models/generated"
)

func newSetVideo(db *gorm.DB, opts ...gen.DOOption) setVideo {
	_setVideo := setVideo{}

	_setVideo.setVideoDo.UseDB(db, opts...)
	_setVideo.setVideoDo.UseModel(&generated.SetVideo{})

	tableName := _setVideo.setVideoDo.TableName()
	_setVideo.ALL = field.NewAsterisk(tableName)
	_setVideo.ID = field.NewField(tableName, "id")
	_setVideo.SetLogID = field.NewField(tableName, "set_log_id")
	_setVideo.UserID = field.NewField(tableName, "user_id")
	_setVideo.Status = field.NewString(tableName, "status")
	_setVideo.StorageKey = field.NewString(tableName, "storage_key")
	_setVideo.ContentType = field.NewString(tableName, "content_type")
	_setVideo.SizeBytes = field.NewInt64(tableName, "size_bytes")
	_setVideo.DurationSec = field.NewFloat64(tableName, "duration_sec")
	_setVideo.OriginalName = field.NewString(tableName, "original_name")
	_setVideo.Note = field.NewString(tableName, "note")
	_setVideo.CreatedAt = field.NewTime(tableName, "created_at")
	_setVideo.UpdatedAt = field.NewTime(tableName, "updated_at")
	_setVideo.DeletedAt = field.NewField(tableName, "deleted_at")

	_setVideo.fillFieldMap()

	return _setVideo
}

type setVideo struct {
	setVideoDo setVideoDo

	ALL          field.Asterisk
	ID           field.Field
	SetLogID     field.Field
	UserID       field.Field
	Status       field.String
	StorageKey   field.String
	ContentType  field.String
	SizeBytes    field.Int64
	DurationSec  field.Float64
	OriginalName field.String
	Note         field.String
	CreatedAt    field.Time
	UpdatedAt    field.Time
	DeletedAt    field.Field

	fieldMap map[string]field.Expr
}

func (s setVideo) Table(newTableName string) *setVideo {
	s.setVideoDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s setVideo) As(alias string) *setVideo {
	s.setVideoDo.DO = *(s.setVideoDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *setVideo) updateTableName(table string) *setVideo {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewField(table, "id")
	s.SetLogID = field.NewField(table, "set_log_id")
	s.UserID = field.NewField(table, "user_id")
	s.Status = field.NewString(table, "status")
	s.StorageKey = field.NewString(table, "storage_key")
	s.ContentType = field.NewString(table, "content_type")
	s.SizeBytes = field.NewInt64(table, "size_bytes")
	s.DurationSec = field.NewFloat64(table, "duration_sec")
	s.OriginalName = field.NewString(table, "original_name")
	s.Note = field.NewString(table, "note")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.DeletedAt = field.NewField(table, "deleted_at")

	s.fillFieldMap()

	return s
}

func (s *setVideo) WithContext(ctx context.Context) *setVideoDo { return s.setVideoDo.WithContext(ctx) }

func (s setVideo) TableName() string { return s.setVideoDo.TableName() }

func (s setVideo) Alias() string { return s.setVideoDo.Alias() }

func (s setVideo) Columns(cols ...field.Expr) gen.Columns { return s.setVideoDo.Columns(cols...) }

func (s *setVideo) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *setVideo) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 13)
	s.fieldMap["id"] = s.ID
	s.fieldMap["set_log_id"] = s.SetLogID
	s.fieldMap["user_id"] = s.UserID
	s.fieldMap["status"] = s.Status
	s.fieldMap["storage_key"] = s.StorageKey
	s.fieldMap["content_type"] = s.ContentType
	s.fieldMap["size_bytes"] = s.SizeBytes
	s.fieldMap["duration_sec"] = s.DurationSec
	s.fieldMap["original_name"] = s.OriginalName
	s.fieldMap["note"] = s.Note
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["deleted_at"] = s.DeletedAt
}

func (s setVideo) clone(db *gorm.DB) setVideo {
	s.setVideoDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s setVideo) replaceDB(db *gorm.DB) setVideo {
	s.setVideoDo.ReplaceDB(db)
	return s
}

type setVideoDo struct{ gen.DO }

func (s setVideoDo) Debug() *setVideoDo {
	return s.withDO(s.DO.Debug())
}

func (s setVideoDo) WithContext(ctx context.Context) *setVideoDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s setVideoDo) ReadDB() *setVideoDo {
	return s.Clauses(dbresolver.Read)
}

func (s setVideoDo) WriteDB() *setVideoDo {
	return s.Clauses(dbresolver.Write)
}

func (s setVideoDo) Session(config *gorm.Session) *setVideoDo {
	return s.withDO(s.DO.Session(config))
}

func (s setVideoDo) Clauses(conds ...clause.Expression) *setVideoDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s setVideoDo) Returning(value interface{}, columns ...string) *setVideoDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s setVideoDo) Not(conds ...gen.Condition) *setVideoDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s setVideoDo) Or(conds ...gen.Condition) *setVideoDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s setVideoDo) Select(conds ...field.Expr) *setVideoDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s setVideoDo) Where(conds ...gen.Condition) *setVideoDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s setVideoDo) Order(conds ...field.Expr) *setVideoDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s setVideoDo) Distinct(cols ...field.Expr) *setVideoDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s setVideoDo) Omit(cols ...field.Expr) *setVideoDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s setVideoDo) Join(table schema.Tabler, on ...field.Expr) *setVideoDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s setVideoDo) LeftJoin(table schema.Tabler, on ...field.Expr) *setVideoDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s setVideoDo) RightJoin(table schema.Tabler, on ...field.Expr) *setVideoDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s setVideoDo) Group(cols ...field.Expr) *setVideoDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s setVideoDo) Having(conds ...gen.Condition) *setVideoDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s setVideoDo) Limit(limit int) *setVideoDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s setVideoDo) Offset(offset int) *setVideoDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s setVideoDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *setVideoDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s setVideoDo) Unscoped() *setVideoDo {
	return s.withDO(s.DO.Unscoped())
}

func (s setVideoDo) Create(values ...*generated.SetVideo) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s setVideoDo) CreateInBatches(values []*generated.SetVideo, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s setVideoDo) Save(values ...*generated.SetVideo) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s setVideoDo) First() (*generated.SetVideo, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*generated.SetVideo), nil
	}
}

func (s setVideoDo) Take() (*generated.SetVideo, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*generated.SetVideo), nil
	}
}

func (s setVideoDo) Last() (*generated.SetVideo, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*generated.SetVideo), nil
	}
}

func (s setVideoDo) Find() ([]*generated.SetVideo, error) {
	result, err := s.DO.Find()
	return result.([]*generated.SetVideo), err
}

func (s setVideoDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*generated.SetVideo, err error) {
	buf := make([]*generated.SetVideo, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s setVideoDo) FindInBatches(result *[]*generated.SetVideo, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s setVideoDo) Attrs(attrs ...field.AssignExpr) *setVideoDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s setVideoDo) Assign(attrs ...field.AssignExpr) *setVideoDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s setVideoDo) Joins(fields ...field.RelationField) *setVideoDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s setVideoDo) Preload(fields ...field.RelationField) *setVideoDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s setVideoDo) FirstOrInit() (*generated.SetVideo, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*generated.SetVideo), nil
	}
}

func (s setVideoDo) FirstOrCreate() (*generated.SetVideo, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*generated.SetVideo), nil
	}
}

func (s setVideoDo) FindByPage(offset int, limit int) (result []*generated.SetVideo, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s setVideoDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s setVideoDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s setVideoDo) Delete(models ...*generated.SetVideo) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *setVideoDo) withDO(do gen.Dao) *setVideoDo {
	s.DO = *do.(*gen.DO)
	return s
}
