// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/thompsonlogan/fitlytics/backend/internal/models/generated"
)

func newUserMetric(db *gorm.DB, opts ...gen.DOOption) userMetric {
	_userMetric := userMetric{}

	_userMetric.userMetricDo.UseDB(db, opts...)
	_userMetric.userMetricDo.UseModel(&generated.UserMetric{})

	tableName := _userMetric.userMetricDo.TableName()
	_userMetric.ALL = field.NewAsterisk(tableName)
	_userMetric.ID = field.NewField(tableName, "id")
	_userMetric.UserID = field.NewField(tableName, "user_id")
	_userMetric.RecordedAt = field.NewTime(tableName, "recorded_at")
	_userMetric.BodyweightKg = field.NewFloat64(tableName, "bodyweight_kg")
	_userMetric.SleepHours = field.NewFloat64(tableName, "sleep_hours")
	_userMetric.SleepScore = field.NewInt32(tableName, "sleep_score")
	_userMetric.Soreness = field.NewInt32(tableName, "soreness")
	_userMetric.Fatigue = field.NewInt32(tableName, "fatigue")
	_userMetric.Notes = field.NewString(tableName, "notes")
	_userMetric.Extras = field.NewField(tableName, "extras")
	_userMetric.CreatedAt = field.NewTime(tableName, "created_at")
	_userMetric.UpdatedAt = field.NewTime(tableName, "updated_at")

	_userMetric.fillFieldMap()

	return _userMetric
}

type userMetric struct {
	userMetricDo userMetricDo

	ALL          field.Asterisk
	ID           field.Field
	UserID       field.Field
	RecordedAt   field.Time
	BodyweightKg field.Float64
	SleepHours   field.Float64
	SleepScore   field.Int32
	Soreness     field.Int32
	Fatigue      field.Int32
	Notes        field.String
	Extras       field.Field
	CreatedAt    field.Time
	UpdatedAt    field.Time

	fieldMap map[string]field.Expr
}

func (u userMetric) Table(newTableName string) *userMetric {
	u.userMetricDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userMetric) As(alias string) *userMetric {
	u.userMetricDo.DO = *(u.userMetricDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userMetric) updateTableName(table string) *userMetric {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewField(table, "id")
	u.UserID = field.NewField(table, "user_id")
	u.RecordedAt = field.NewTime(table, "recorded_at")
	u.BodyweightKg = field.NewFloat64(table, "bodyweight_kg")
	u.SleepHours = field.NewFloat64(table, "sleep_hours")
	u.SleepScore = field.NewInt32(table, "sleep_score")
	u.Soreness = field.NewInt32(table, "soreness")
	u.Fatigue = field.NewInt32(table, "fatigue")
	u.Notes = field.NewString(table, "notes")
	u.Extras = field.NewField(table, "extras")
	u.CreatedAt = field.NewTime(table, "created_at")
	u.UpdatedAt = field.NewTime(table, "updated_at")

	u.fillFieldMap()

	return u
}

func (u *userMetric) WithContext(ctx context.Context) *userMetricDo {
	return u.userMetricDo.WithContext(ctx)
}

func (u userMetric) TableName() string { return u.userMetricDo.TableName() }

func (u userMetric) Alias() string { return u.userMetricDo.Alias() }

func (u userMetric) Columns(cols ...field.Expr) gen.Columns { return u.userMetricDo.Columns(cols...) }

func (u *userMetric) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userMetric) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 12)
	u.fieldMap["id"] = u.ID
	u.fieldMap["user_id"] = u.UserID
	u.fieldMap["recorded_at"] = u.RecordedAt
	u.fieldMap["bodyweight_kg"] = u.BodyweightKg
	u.fieldMap["sleep_hours"] = u.SleepHours
	u.fieldMap["sleep_score"] = u.SleepScore
	u.fieldMap["soreness"] = u.Soreness
	u.fieldMap["fatigue"] = u.Fatigue
	u.fieldMap["notes"] = u.Notes
	u.fieldMap["extras"] = u.Extras
	u.fieldMap["created_at"] = u.CreatedAt
	u.fieldMap["updated_at"] = u.UpdatedAt
}

func (u userMetric) clone(db *gorm.DB) userMetric {
	u.userMetricDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u userMetric) replaceDB(db *gorm.DB) userMetric {
	u.userMetricDo.ReplaceDB(db)
	return u
}

type userMetricDo struct{ gen.DO }

func (u userMetricDo) Debug() *userMetricDo {
	return u.withDO(u.DO.Debug())
}

func (u userMetricDo) WithContext(ctx context.Context) *userMetricDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userMetricDo) ReadDB() *userMetricDo {
	return u.Clauses(dbresolver.Read)
}

func (u userMetricDo) WriteDB() *userMetricDo {
	return u.Clauses(dbresolver.Write)
}

func (u userMetricDo) Session(config *gorm.Session) *userMetricDo {
	return u.withDO(u.DO.Session(config))
}

func (u userMetricDo) Clauses(conds ...clause.Expression) *userMetricDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userMetricDo) Returning(value interface{}, columns ...string) *userMetricDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userMetricDo) Not(conds ...gen.Condition) *userMetricDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userMetricDo) Or(conds ...gen.Condition) *userMetricDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userMetricDo) Select(conds ...field.Expr) *userMetricDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userMetricDo) Where(conds ...gen.Condition) *userMetricDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userMetricDo) Order(conds ...field.Expr) *userMetricDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userMetricDo) Distinct(cols ...field.Expr) *userMetricDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userMetricDo) Omit(cols ...field.Expr) *userMetricDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userMetricDo) Join(table schema.Tabler, on ...field.Expr) *userMetricDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userMetricDo) LeftJoin(table schema.Tabler, on ...field.Expr) *userMetricDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userMetricDo) RightJoin(table schema.Tabler, on ...field.Expr) *userMetricDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userMetricDo) Group(cols ...field.Expr) *userMetricDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userMetricDo) Having(conds ...gen.Condition) *userMetricDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userMetricDo) Limit(limit int) *userMetricDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userMetricDo) Offset(offset int) *userMetricDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userMetricDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *userMetricDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userMetricDo) Unscoped() *userMetricDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userMetricDo) Create(values ...*generated.UserMetric) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userMetricDo) CreateInBatches(values []*generated.UserMetric, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userMetricDo) Save(values ...*generated.UserMetric) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userMetricDo) First() (*generated.UserMetric, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*generated.UserMetric), nil
	}
}

func (u userMetricDo) Take() (*generated.UserMetric, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*generated.UserMetric), nil
	}
}

func (u userMetricDo) Last() (*generated.UserMetric, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*generated.UserMetric), nil
	}
}

func (u userMetricDo) Find() ([]*generated.UserMetric, error) {
	result, err := u.DO.Find()
	return result.([]*generated.UserMetric), err
}

func (u userMetricDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*generated.UserMetric, err error) {
	buf := make([]*generated.UserMetric, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userMetricDo) FindInBatches(result *[]*generated.UserMetric, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userMetricDo) Attrs(attrs ...field.AssignExpr) *userMetricDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userMetricDo) Assign(attrs ...field.AssignExpr) *userMetricDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userMetricDo) Joins(fields ...field.RelationField) *userMetricDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userMetricDo) Preload(fields ...field.RelationField) *userMetricDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userMetricDo) FirstOrInit() (*generated.UserMetric, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*generated.UserMetric), nil
	}
}

func (u userMetricDo) FirstOrCreate() (*generated.UserMetric, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*generated.UserMetric), nil
	}
}

func (u userMetricDo) FindByPage(offset int, limit int) (result []*generated.UserMetric, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userMetricDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userMetricDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userMetricDo) Delete(models ...*generated.UserMetric) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userMetricDo) withDO(do gen.Dao) *userMetricDo {
	u.DO = *do.(*gen.DO)
	return u
}
