// Command api is the fitlytics backend HTTP service.
//
// @title                       Fitlytics API
// @version                     0.1
// @description                 Workout tracking and training analytics API. Protected routes require a WorkOS access token in the `Authorization: Bearer ...` header.
// @BasePath                    /
// @schemes                     http https
// @securityDefinitions.apikey  BearerAuth
// @in                          header
// @name                        Authorization
// @description                 WorkOS access token. Send as `Bearer <token>`.
package main

import (
	"context"
	"os"
	"os/signal"
	"syscall"

	// docs is generated by `make swagger` and registers the OpenAPI spec on
	// swag's default instance. Blank import is intentional — we only need the
	// init() side effect.
	_ "github.com/thompsonlogan/fitlytics/backend/docs"

	"github.com/google/uuid"
	"github.com/thompsonlogan/fitlytics/backend/internal/auth"
	"github.com/thompsonlogan/fitlytics/backend/internal/config"
	"github.com/thompsonlogan/fitlytics/backend/internal/database"
	"github.com/thompsonlogan/fitlytics/backend/internal/handlers"
	"github.com/thompsonlogan/fitlytics/backend/internal/logger"
	"github.com/thompsonlogan/fitlytics/backend/internal/server"
	"github.com/thompsonlogan/fitlytics/backend/internal/users"
)

func main() {
	cfg, err := config.Load()
	if err != nil {
		// Logger isn't built yet; fail loudly on stderr.
		println("config error:", err.Error())
		os.Exit(1)
	}

	log := logger.New(cfg.LogLevel, cfg.Env)

	// Root context cancelled on SIGINT/SIGTERM — drives graceful shutdown and
	// the lifetime of the JWKS background refresh.
	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer stop()

	db, err := database.Connect(ctx, cfg.DatabaseURL, log)
	if err != nil {
		log.Error("database connection failed", "error", err)
		os.Exit(1)
	}

	verifier, err := auth.NewVerifier(ctx, cfg.JWKSURL, cfg.JWTIssuer)
	if err != nil {
		log.Error("auth verifier setup failed", "error", err)
		os.Exit(1)
	}

	workosClient := auth.NewWorkOSClient(cfg.WorkOSAPIKey)
	userService := users.NewService(db, workosClient)

	var bypassUserID uuid.UUID
	if cfg.AuthBypassUserID != "" {
		parsed, err := uuid.Parse(cfg.AuthBypassUserID)
		if err != nil {
			log.Error("invalid AUTH_BYPASS_USER_ID — must be a valid UUID", "value", cfg.AuthBypassUserID)
			os.Exit(1)
		}
		if cfg.IsProduction() {
			log.Error("AUTH_BYPASS_USER_ID cannot be set in production")
			os.Exit(1)
		}
		bypassUserID = parsed
	}

	router := server.NewRouter(server.Dependencies{
		DB:               db,
		Verifier:         verifier,
		Users:            userService,
		Log:              log,
		AuthBypassUserID: bypassUserID,
		Auth: handlers.AuthDeps{
			ClientID:    cfg.WorkOSClientID,
			RedirectURI: cfg.WorkOSRedirectURI,
			AppURL:      cfg.AppURL,
			Cookies:     auth.CookieOpts{Secure: cfg.IsProduction()},
			Verifier:    verifier,
			Log:         log,
		},
	}, cfg.IsProduction())

	if err := server.Run(ctx, ":"+cfg.HTTPPort, router, log); err != nil {
		log.Error("server stopped with error", "error", err)
		os.Exit(1)
	}
	log.Info("server stopped cleanly")
}
