// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID           uuid.UUID      `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	WorkosUserID string         `gorm:"column:workos_user_id;type:text;not null" json:"workos_user_id"`
	DisplayName  string         `gorm:"column:display_name;type:text;not null" json:"display_name"`
	Email        *string        `gorm:"column:email;type:text" json:"email"`
	UnitPref     string         `gorm:"column:unit_pref;type:unit_system;not null;default:imperial" json:"unit_pref"`
	Timezone     string         `gorm:"column:timezone;type:text;not null;default:UTC" json:"timezone"`
	CreatedAt    time.Time      `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt    time.Time      `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone" json:"deleted_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
