// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"

	"github.com/google/uuid"
)

const TableNameUserMetric = "user_metrics"

// UserMetric mapped from table <user_metrics>
type UserMetric struct {
	ID           uuid.UUID `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	UserID       uuid.UUID `gorm:"column:user_id;type:uuid;not null" json:"user_id"`
	RecordedAt   time.Time `gorm:"column:recorded_at;type:timestamp with time zone;not null;default:now()" json:"recorded_at"`
	BodyweightKg *float64  `gorm:"column:bodyweight_kg;type:numeric(5,2)" json:"bodyweight_kg"`
	SleepHours   *float64  `gorm:"column:sleep_hours;type:numeric(4,2)" json:"sleep_hours"`
	SleepScore   *int32    `gorm:"column:sleep_score;type:integer" json:"sleep_score"`
	Soreness     *int32    `gorm:"column:soreness;type:integer" json:"soreness"`
	Fatigue      *int32    `gorm:"column:fatigue;type:integer" json:"fatigue"`
	Notes        *string   `gorm:"column:notes;type:text" json:"notes"`
	Extras       JSONB     `gorm:"column:extras;type:jsonb;not null;default:{}" json:"extras"`
	CreatedAt    time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
}

// TableName UserMetric's table name
func (*UserMetric) TableName() string {
	return TableNameUserMetric
}
